//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 03:52:20 PM CEST 
//


package uz.ehealth.ritme.be.fgov.ehealth.commons.protocol.v2;

import uz.ehealth.ritme.be.fgov.ehealth.addressbook.protocol.v1.SearchOrganizationsRequestType;
import uz.ehealth.ritme.be.fgov.ehealth.addressbook.protocol.v1.SearchProfessionalsRequestType;

import javax.xml.bind.annotation.*;


/**
 * eHealth SOA Request Type for Services that require a Pagination as input.
 * 
 * <p>Java class for PaginationRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaginationRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:commons:protocol:v2}RequestType">
 *       &lt;attGroup ref="{urn:be:fgov:ehealth:commons:core:v2}PaginationAttributeGroup"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("ALL") //Generated file
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaginationRequestType")
@XmlSeeAlso({
    SearchProfessionalsRequestType.class,
    SearchOrganizationsRequestType.class
})
public class PaginationRequestType
    extends RequestType
{

    @XmlAttribute(name = "Offset", required = true)
    protected int offset;
    @XmlAttribute(name = "MaxElements", required = true)
    protected int maxElements;

    /**
     * Gets the value of the offset property.
     * 
     */
    public int getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(int value) {
        this.offset = value;
    }

    /**
     * Gets the value of the maxElements property.
     * 
     */
    public int getMaxElements() {
        return maxElements;
    }

    /**
     * Sets the value of the maxElements property.
     * 
     */
    public void setMaxElements(int value) {
        this.maxElements = value;
    }

}
