//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 11:40:37 AM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import be.apb.standards.smoa.schema.v1.QuantityPrefix;
import be.apb.standards.smoa.schema.v1.QuantityType;


/**
 * <p>Java class for compoundType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="compoundType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="order" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;choice>
 *           &lt;element name="medicinalproduct">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="intendedProduct" type="{http://www.apb.be/standards/smoa/schema/v1}CnkType"/>
 *                     &lt;element name="deliveredProduct" type="{http://www.apb.be/standards/smoa/schema/v1}CnkType" minOccurs="0"/>
 *                     &lt;element name="intendedname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="deliveredname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="substance">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="substancecode" type="{http://www.apb.be/standards/smoa/schema/v1}CnkType"/>
 *                     &lt;element name="substancename" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="quantityprefix" type="{http://www.apb.be/standards/smoa/schema/v1}QuantityPrefix" minOccurs="0"/>
 *         &lt;element name="quantity" type="{http://www.apb.be/standards/smoa/schema/v1}QuantityType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "compoundType", propOrder = {
    "order",
    "medicinalproduct",
    "substance",
    "quantityprefix",
    "quantity"
})
public class CompoundType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger order;
    protected CompoundType.Medicinalproduct medicinalproduct;
    protected CompoundType.Substance substance;
    protected QuantityPrefix quantityprefix;
    protected QuantityType quantity;

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrder(BigInteger value) {
        this.order = value;
    }

    /**
     * Gets the value of the medicinalproduct property.
     * 
     * @return
     *     possible object is
     *     {@link CompoundType.Medicinalproduct }
     *     
     */
    public CompoundType.Medicinalproduct getMedicinalproduct() {
        return medicinalproduct;
    }

    /**
     * Sets the value of the medicinalproduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompoundType.Medicinalproduct }
     *     
     */
    public void setMedicinalproduct(CompoundType.Medicinalproduct value) {
        this.medicinalproduct = value;
    }

    /**
     * Gets the value of the substance property.
     * 
     * @return
     *     possible object is
     *     {@link CompoundType.Substance }
     *     
     */
    public CompoundType.Substance getSubstance() {
        return substance;
    }

    /**
     * Sets the value of the substance property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompoundType.Substance }
     *     
     */
    public void setSubstance(CompoundType.Substance value) {
        this.substance = value;
    }

    /**
     * Gets the value of the quantityprefix property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityPrefix }
     *     
     */
    public QuantityPrefix getQuantityprefix() {
        return quantityprefix;
    }

    /**
     * Sets the value of the quantityprefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityPrefix }
     *     
     */
    public void setQuantityprefix(QuantityPrefix value) {
        this.quantityprefix = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setQuantity(QuantityType value) {
        this.quantity = value;
    }


    /**
     * a medicinal product can be identified unambiguously by a CNK code identifying a package. The descriptive identification is only mandatory in case of absence of a package ID.
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="intendedProduct" type="{http://www.apb.be/standards/smoa/schema/v1}CnkType"/>
     *         &lt;element name="deliveredProduct" type="{http://www.apb.be/standards/smoa/schema/v1}CnkType" minOccurs="0"/>
     *         &lt;element name="intendedname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="deliveredname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "intendedProduct",
        "deliveredProduct",
        "intendedname",
        "deliveredname"
    })
    public static class Medicinalproduct
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected String intendedProduct;
        protected String deliveredProduct;
        @XmlElement(required = true)
        protected String intendedname;
        protected String deliveredname;

        /**
         * Gets the value of the intendedProduct property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIntendedProduct() {
            return intendedProduct;
        }

        /**
         * Sets the value of the intendedProduct property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIntendedProduct(String value) {
            this.intendedProduct = value;
        }

        /**
         * Gets the value of the deliveredProduct property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveredProduct() {
            return deliveredProduct;
        }

        /**
         * Sets the value of the deliveredProduct property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveredProduct(String value) {
            this.deliveredProduct = value;
        }

        /**
         * Gets the value of the intendedname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIntendedname() {
            return intendedname;
        }

        /**
         * Sets the value of the intendedname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIntendedname(String value) {
            this.intendedname = value;
        }

        /**
         * Gets the value of the deliveredname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveredname() {
            return deliveredname;
        }

        /**
         * Sets the value of the deliveredname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveredname(String value) {
            this.deliveredname = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="substancecode" type="{http://www.apb.be/standards/smoa/schema/v1}CnkType"/>
     *         &lt;element name="substancename" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "substancecode",
        "substancename"
    })
    public static class Substance
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected String substancecode;
        @XmlElement(required = true)
        protected String substancename;

        /**
         * Gets the value of the substancecode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubstancecode() {
            return substancecode;
        }

        /**
         * Sets the value of the substancecode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubstancecode(String value) {
            this.substancecode = value;
        }

        /**
         * Gets the value of the substancename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubstancename() {
            return substancename;
        }

        /**
         * Sets the value of the substancename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubstancename(String value) {
            this.substancename = value;
        }

    }

}
