//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for formularyReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="formularyReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="formulaCode" type="{http://www.apb.be/standards/smoa/schema/v1}CnkType"/>
 *         &lt;element name="formulaName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formulary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formularyReferenceType", propOrder = {
    "formulaCode",
    "formulaName",
    "formulary"
})
public class FormularyReferenceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String formulaCode;
    @XmlElement(required = true)
    protected String formulaName;
    @XmlElement(required = true)
    protected String formulary;

    /**
     * Gets the value of the formulaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormulaCode() {
        return formulaCode;
    }

    /**
     * Sets the value of the formulaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormulaCode(String value) {
        this.formulaCode = value;
    }

    /**
     * Gets the value of the formulaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormulaName() {
        return formulaName;
    }

    /**
     * Sets the value of the formulaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormulaName(String value) {
        this.formulaName = value;
    }

    /**
     * Gets the value of the formulary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormulary() {
        return formulary;
    }

    /**
     * Sets the value of the formulary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormulary(String value) {
        this.formulary = value;
    }

}
