//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.02 at 01:27:32 PM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InsuredStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuredStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cg1" type="{http://www.apb.be/standards/smoa/schema/v1}CodeStatusMutuality" minOccurs="0"/>
 *         &lt;element name="cg2" type="{http://www.apb.be/standards/smoa/schema/v1}CodeStatusMutuality" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuredStatus", propOrder = {
    "cg1",
    "cg2"
})
public class InsuredStatus
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(defaultValue = "000")
    protected String cg1;
    @XmlElement(defaultValue = "000")
    protected String cg2;

    /**
     * Gets the value of the cg1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCg1() {
        return cg1;
    }

    /**
     * Sets the value of the cg1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCg1(String value) {
        this.cg1 = value;
    }

    /**
     * Gets the value of the cg2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCg2() {
        return cg2;
    }

    /**
     * Sets the value of the cg2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCg2(String value) {
        this.cg2 = value;
    }

}
