//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MagistralType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MagistralType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.apb.be/standards/smoa/schema/model/v1}abstract-Preparation"/>
 *         &lt;element ref="{http://www.apb.be/standards/smoa/schema/model/v1}abstract-MagistralCertificate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MagistralType", propOrder = {
    "abstractPreparation",
    "abstractMagistralCertificate"
})
public class MagistralType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "abstract-Preparation", namespace = "http://www.apb.be/standards/smoa/schema/model/v1", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractPreparationType> abstractPreparation;
    @XmlElementRef(name = "abstract-MagistralCertificate", namespace = "http://www.apb.be/standards/smoa/schema/model/v1", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractMagistralCertificateType> abstractMagistralCertificate;

    /**
     * Gets the value of the abstractPreparation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AbstractPreparationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PreparationType }{@code >}
     *     
     */
    public JAXBElement<? extends AbstractPreparationType> getAbstractPreparation() {
        return abstractPreparation;
    }

    /**
     * Sets the value of the abstractPreparation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AbstractPreparationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PreparationType }{@code >}
     *     
     */
    public void setAbstractPreparation(JAXBElement<? extends AbstractPreparationType> value) {
        this.abstractPreparation = ((JAXBElement<? extends AbstractPreparationType> ) value);
    }

    /**
     * Gets the value of the abstractMagistralCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MagistralCertificateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractMagistralCertificateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractMagistralCertificateType }{@code >}
     *     
     */
    public JAXBElement<? extends AbstractMagistralCertificateType> getAbstractMagistralCertificate() {
        return abstractMagistralCertificate;
    }

    /**
     * Sets the value of the abstractMagistralCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MagistralCertificateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractMagistralCertificateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractMagistralCertificateType }{@code >}
     *     
     */
    public void setAbstractMagistralCertificate(JAXBElement<? extends AbstractMagistralCertificateType> value) {
        this.abstractMagistralCertificate = ((JAXBElement<? extends AbstractMagistralCertificateType> ) value);
    }

}
