//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import be.apb.standards.smoa.schema.id.v1.AbstractMedicinalProductIdType;


/**
 * <p>Java class for MinSetProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MinSetProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="productCode" type="{http://www.apb.be/standards/smoa/schema/id/v1}Abstract-MedicinalProductIdType"/>
 *                   &lt;element name="magistralPreparation" type="{http://www.apb.be/standards/smoa/schema/model/v1}MagistralPreparationType"/>
 *                   &lt;element name="unregisteredProduct" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dispensation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numberOfUnits" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="administrationInstructions" type="{http://www.apb.be/standards/smoa/schema/model/v1}AdministrationType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MinSetProductType", propOrder = {
    "description",
    "dispensation"
})
@XmlSeeAlso({
    HistoryProductType.class,
    MaxSetProductType.class
})
public class MinSetProductType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected MinSetProductType.Description description;
    @XmlElement(required = true)
    protected MinSetProductType.Dispensation dispensation;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link MinSetProductType.Description }
     *     
     */
    public MinSetProductType.Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinSetProductType.Description }
     *     
     */
    public void setDescription(MinSetProductType.Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the dispensation property.
     * 
     * @return
     *     possible object is
     *     {@link MinSetProductType.Dispensation }
     *     
     */
    public MinSetProductType.Dispensation getDispensation() {
        return dispensation;
    }

    /**
     * Sets the value of the dispensation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MinSetProductType.Dispensation }
     *     
     */
    public void setDispensation(MinSetProductType.Dispensation value) {
        this.dispensation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="productCode" type="{http://www.apb.be/standards/smoa/schema/id/v1}Abstract-MedicinalProductIdType"/>
     *         &lt;element name="magistralPreparation" type="{http://www.apb.be/standards/smoa/schema/model/v1}MagistralPreparationType"/>
     *         &lt;element name="unregisteredProduct" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productCode",
        "magistralPreparation",
        "unregisteredProduct"
    })
    public static class Description
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected AbstractMedicinalProductIdType productCode;
        protected MagistralPreparationType magistralPreparation;
        protected String unregisteredProduct;

        /**
         * Gets the value of the productCode property.
         * 
         * @return
         *     possible object is
         *     {@link AbstractMedicinalProductIdType }
         *     
         */
        public AbstractMedicinalProductIdType getProductCode() {
            return productCode;
        }

        /**
         * Sets the value of the productCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link AbstractMedicinalProductIdType }
         *     
         */
        public void setProductCode(AbstractMedicinalProductIdType value) {
            this.productCode = value;
        }

        /**
         * Gets the value of the magistralPreparation property.
         * 
         * @return
         *     possible object is
         *     {@link MagistralPreparationType }
         *     
         */
        public MagistralPreparationType getMagistralPreparation() {
            return magistralPreparation;
        }

        /**
         * Sets the value of the magistralPreparation property.
         * 
         * @param value
         *     allowed object is
         *     {@link MagistralPreparationType }
         *     
         */
        public void setMagistralPreparation(MagistralPreparationType value) {
            this.magistralPreparation = value;
        }

        /**
         * Gets the value of the unregisteredProduct property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnregisteredProduct() {
            return unregisteredProduct;
        }

        /**
         * Sets the value of the unregisteredProduct property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnregisteredProduct(String value) {
            this.unregisteredProduct = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numberOfUnits" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="administrationInstructions" type="{http://www.apb.be/standards/smoa/schema/model/v1}AdministrationType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numberOfUnits",
        "administrationInstructions"
    })
    public static class Dispensation
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected Integer numberOfUnits;
        protected AdministrationType administrationInstructions;

        /**
         * Gets the value of the numberOfUnits property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumberOfUnits() {
            return numberOfUnits;
        }

        /**
         * Sets the value of the numberOfUnits property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumberOfUnits(Integer value) {
            this.numberOfUnits = value;
        }

        /**
         * Gets the value of the administrationInstructions property.
         * 
         * @return
         *     possible object is
         *     {@link AdministrationType }
         *     
         */
        public AdministrationType getAdministrationInstructions() {
            return administrationInstructions;
        }

        /**
         * Sets the value of the administrationInstructions property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdministrationType }
         *     
         */
        public void setAdministrationInstructions(AdministrationType value) {
            this.administrationInstructions = value;
        }

    }

}
