//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.01 at 04:59:58 AM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.apb.standards.smoa.schema.model.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RefPharmacy_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "refPharmacy");
    private final static QName _DataLocation_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "dataLocation");
    private final static QName _RefMagistralCertificate_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "refMagistralCertificate");
    private final static QName _ContactPerson_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "contactPerson");
    private final static QName _AbstractTelecom_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Telecom");
    private final static QName _PatientPrescription_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "patientPrescription");
    private final static QName _AbstractHumanPrescription_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-HumanPrescription");
    private final static QName _AbstractAddress_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Address");
    private final static QName _MedicationConsumerAnimalOwner_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "medicationConsumerAnimalOwner");
    private final static QName _DeliveredMedicationHuman_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "deliveredMedicationHuman");
    private final static QName _RefPrescription_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "refPrescription");
    private final static QName _MaxPatient_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "max-Patient");
    private final static QName _AbstractPharmacist_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Pharmacist");
    private final static QName _AbstractPerson_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Person");
    private final static QName _MagistralCertificate_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "magistralCertificate");
    private final static QName _MedicationConsumerPatient_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "medicationConsumerPatient");
    private final static QName _Identification_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "identification");
    private final static QName _Regimen_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "regimen");
    private final static QName _MedicinalProduct_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "medicinalProduct");
    private final static QName _AbstractVeterinaryPrescription_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-VeterinaryPrescription");
    private final static QName _VeterinaryPrescription_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "veterinaryPrescription");
    private final static QName _AbstractSupplier_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Supplier");
    private final static QName _DeferredPrescription_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "deferredPrescription");
    private final static QName _Posology_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "posology");
    private final static QName _AbstractRawMaterial_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-RawMaterial");
    private final static QName _RawMaterial_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "rawMaterial");
    private final static QName _RecipeLine_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "recipeLine");
    private final static QName _AbstractDataLocation_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-DataLocation");
    private final static QName _MedicationHistoryEntity_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "medicationHistoryEntity");
    private final static QName _SubstanceProduct_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "substanceProduct");
    private final static QName _AbstractMedicationConsumer_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-MedicationConsumer");
    private final static QName _KmehrPrescription_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "kmehrPrescription");
    private final static QName _StatusMessage_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "statusMessage");
    private final static QName _AbstractCareService_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-CareService");
    private final static QName _AbstractRecipeLine_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-RecipeLine");
    private final static QName _AbstractStatusMessage_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-StatusMessage");
    private final static QName _MedicationConsumerUrgentieTrousse_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "medicationConsumerUrgentieTrousse");
    private final static QName _Preparation_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "preparation");
    private final static QName _AbstractMedicinalProduct_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-MedicinalProduct");
    private final static QName _AbstractSubstanceProduct_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-SubstanceProduct");
    private final static QName _AbstractPharmacy_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Pharmacy");
    private final static QName _AbstractCareProvider_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-CareProvider");
    private final static QName _AbstractPatient_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Patient");
    private final static QName _Person_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "person");
    private final static QName _AbstractMagistralCertificate_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-MagistralCertificate");
    private final static QName _RefPerson_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "refPerson");
    private final static QName _AbstractPreparation_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Preparation");
    private final static QName _MinPatient_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "min-Patient");
    private final static QName _AbstractPosology_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Posology");
    private final static QName _SpecialPrescription_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "specialPrescription");
    private final static QName _AbstractPrescription_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Prescription");
    private final static QName _AbstractDeliveredMedication_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-DeliveredMedication");
    private final static QName _MedicationConsumerPatientGroup_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "medicationConsumerPatientGroup");
    private final static QName _RefAttest_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "refAttest");
    private final static QName _AbstractEntity_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Entity");
    private final static QName _IncomingMedication_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "incomingMedication");
    private final static QName _AbstractAttest_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Attest");
    private final static QName _RefCareService_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "refCareService");
    private final static QName _Hcparty_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "hcparty");
    private final static QName _AbstractRegimen_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-Regimen");
    private final static QName _RefMedicinalProduct_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "refMedicinalProduct");
    private final static QName _Attest_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "attest");
    private final static QName _DeliveredMedicationVeterinair_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "deliveredMedicationVeterinair");
    private final static QName _AbstractIncomingMedication_QNAME = new QName("http://www.apb.be/standards/smoa/schema/model/v1", "abstract-IncomingMedication");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.apb.standards.smoa.schema.model.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonType.FirstNames }
     * 
     */
    public PersonType.FirstNames createPersonTypeFirstNames() {
        return new PersonType.FirstNames();
    }

    /**
     * Create an instance of {@link Identity }
     * 
     */
    public Identity createIdentity() {
        return new Identity();
    }

    /**
     * Create an instance of {@link NhiData }
     * 
     */
    public NhiData createNhiData() {
        return new NhiData();
    }

    /**
     * Create an instance of {@link RegimenAdministrationQuantityType }
     * 
     */
    public RegimenAdministrationQuantityType createRegimenAdministrationQuantityType() {
        return new RegimenAdministrationQuantityType();
    }

    /**
     * Create an instance of {@link MaxSetPatient.Physiology.ChronicPathologies }
     * 
     */
    public MaxSetPatient.Physiology.ChronicPathologies createMaxSetPatientPhysiologyChronicPathologies() {
        return new MaxSetPatient.Physiology.ChronicPathologies();
    }

    /**
     * Create an instance of {@link RawMaterialType }
     * 
     */
    public RawMaterialType createRawMaterialType() {
        return new RawMaterialType();
    }

    /**
     * Create an instance of {@link DataLocationType }
     * 
     */
    public DataLocationType createDataLocationType() {
        return new DataLocationType();
    }

    /**
     * Create an instance of {@link CompoundType.Medicinalproduct }
     * 
     */
    public CompoundType.Medicinalproduct createCompoundTypeMedicinalproduct() {
        return new CompoundType.Medicinalproduct();
    }

    /**
     * Create an instance of {@link MaxSetProductType }
     * 
     */
    public MaxSetProductType createMaxSetProductType() {
        return new MaxSetProductType();
    }

    /**
     * Create an instance of {@link ProductList }
     * 
     */
    public ProductList createProductList() {
        return new ProductList();
    }

    /**
     * Create an instance of {@link MaxSetPatient.CareProviders }
     * 
     */
    public MaxSetPatient.CareProviders createMaxSetPatientCareProviders() {
        return new MaxSetPatient.CareProviders();
    }

    /**
     * Create an instance of {@link IdentificationBvacDoctor }
     * 
     */
    public IdentificationBvacDoctor createIdentificationBvacDoctor() {
        return new IdentificationBvacDoctor();
    }

    /**
     * Create an instance of {@link BarCode }
     * 
     */
    public BarCode createBarCode() {
        return new BarCode();
    }

    /**
     * Create an instance of {@link MinSetProductType.Description }
     * 
     */
    public MinSetProductType.Description createMinSetProductTypeDescription() {
        return new MinSetProductType.Description();
    }

    /**
     * Create an instance of {@link IncomingMedicationType }
     * 
     */
    public IncomingMedicationType createIncomingMedicationType() {
        return new IncomingMedicationType();
    }

    /**
     * Create an instance of {@link MaxSetPatient }
     * 
     */
    public MaxSetPatient createMaxSetPatient() {
        return new MaxSetPatient();
    }

    /**
     * Create an instance of {@link PatientPrescriptionType }
     * 
     */
    public PatientPrescriptionType createPatientPrescriptionType() {
        return new PatientPrescriptionType();
    }

    /**
     * Create an instance of {@link AdministrationType.Temporality }
     * 
     */
    public AdministrationType.Temporality createAdministrationTypeTemporality() {
        return new AdministrationType.Temporality();
    }

    /**
     * Create an instance of {@link PharmacyList }
     * 
     */
    public PharmacyList createPharmacyList() {
        return new PharmacyList();
    }

    /**
     * Create an instance of {@link MaxSetPatient.Physiology.ChronicPathologies.HomeOxygenTherapy }
     * 
     */
    public MaxSetPatient.Physiology.ChronicPathologies.HomeOxygenTherapy createMaxSetPatientPhysiologyChronicPathologiesHomeOxygenTherapy() {
        return new MaxSetPatient.Physiology.ChronicPathologies.HomeOxygenTherapy();
    }

    /**
     * Create an instance of {@link MedicationConsumerPatientType }
     * 
     */
    public MedicationConsumerPatientType createMedicationConsumerPatientType() {
        return new MedicationConsumerPatientType();
    }

    /**
     * Create an instance of {@link RecipeLinesComplexType }
     * 
     */
    public RecipeLinesComplexType createRecipeLinesComplexType() {
        return new RecipeLinesComplexType();
    }

    /**
     * Create an instance of {@link PharmaceuticalInformationType }
     * 
     */
    public PharmaceuticalInformationType createPharmaceuticalInformationType() {
        return new PharmaceuticalInformationType();
    }

    /**
     * Create an instance of {@link Identification }
     * 
     */
    public Identification createIdentification() {
        return new Identification();
    }

    /**
     * Create an instance of {@link EuropeanAddressType }
     * 
     */
    public EuropeanAddressType createEuropeanAddressType() {
        return new EuropeanAddressType();
    }

    /**
     * Create an instance of {@link IdentificationBvacPatient }
     * 
     */
    public IdentificationBvacPatient createIdentificationBvacPatient() {
        return new IdentificationBvacPatient();
    }

    /**
     * Create an instance of {@link MedicinalProduct }
     * 
     */
    public MedicinalProduct createMedicinalProduct() {
        return new MedicinalProduct();
    }

    /**
     * Create an instance of {@link MaxSetPatient.Entourage }
     * 
     */
    public MaxSetPatient.Entourage createMaxSetPatientEntourage() {
        return new MaxSetPatient.Entourage();
    }

    /**
     * Create an instance of {@link MagistralCertificateType }
     * 
     */
    public MagistralCertificateType createMagistralCertificateType() {
        return new MagistralCertificateType();
    }

    /**
     * Create an instance of {@link DeliveredMedicationVeterinairType }
     * 
     */
    public DeliveredMedicationVeterinairType createDeliveredMedicationVeterinairType() {
        return new DeliveredMedicationVeterinairType();
    }

    /**
     * Create an instance of {@link MaxSetProductType.PharmaceuticalCare.ProductInformation }
     * 
     */
    public MaxSetProductType.PharmaceuticalCare.ProductInformation createMaxSetProductTypePharmaceuticalCareProductInformation() {
        return new MaxSetProductType.PharmaceuticalCare.ProductInformation();
    }

    /**
     * Create an instance of {@link VeterinaryPrescriptionType }
     * 
     */
    public VeterinaryPrescriptionType createVeterinaryPrescriptionType() {
        return new VeterinaryPrescriptionType();
    }

    /**
     * Create an instance of {@link DescriptionBvacProduct }
     * 
     */
    public DescriptionBvacProduct createDescriptionBvacProduct() {
        return new DescriptionBvacProduct();
    }

    /**
     * Create an instance of {@link MinSetProductType }
     * 
     */
    public MinSetProductType createMinSetProductType() {
        return new MinSetProductType();
    }

    /**
     * Create an instance of {@link DataLocationType.Location }
     * 
     */
    public DataLocationType.Location createDataLocationTypeLocation() {
        return new DataLocationType.Location();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link RegimenDayTimeType }
     * 
     */
    public RegimenDayTimeType createRegimenDayTimeType() {
        return new RegimenDayTimeType();
    }

    /**
     * Create an instance of {@link KmehrPrescriptionType }
     * 
     */
    public KmehrPrescriptionType createKmehrPrescriptionType() {
        return new KmehrPrescriptionType();
    }

    /**
     * Create an instance of {@link MaxSetContactPersonType }
     * 
     */
    public MaxSetContactPersonType createMaxSetContactPersonType() {
        return new MaxSetContactPersonType();
    }

    /**
     * Create an instance of {@link MaxSetPatient.Physiology.Condition.Female }
     * 
     */
    public MaxSetPatient.Physiology.Condition.Female createMaxSetPatientPhysiologyConditionFemale() {
        return new MaxSetPatient.Physiology.Condition.Female();
    }

    /**
     * Create an instance of {@link InsuredStatus }
     * 
     */
    public InsuredStatus createInsuredStatus() {
        return new InsuredStatus();
    }

    /**
     * Create an instance of {@link StatusMessageType }
     * 
     */
    public StatusMessageType createStatusMessageType() {
        return new StatusMessageType();
    }

    /**
     * Create an instance of {@link VeterinaryPrescriptionType.Responsible }
     * 
     */
    public VeterinaryPrescriptionType.Responsible createVeterinaryPrescriptionTypeResponsible() {
        return new VeterinaryPrescriptionType.Responsible();
    }

    /**
     * Create an instance of {@link MaxSetProductType.PharmaceuticalCare }
     * 
     */
    public MaxSetProductType.PharmaceuticalCare createMaxSetProductTypePharmaceuticalCare() {
        return new MaxSetProductType.PharmaceuticalCare();
    }

    /**
     * Create an instance of {@link AdministrationType }
     * 
     */
    public AdministrationType createAdministrationType() {
        return new AdministrationType();
    }

    /**
     * Create an instance of {@link PosologyTakesType }
     * 
     */
    public PosologyTakesType createPosologyTakesType() {
        return new PosologyTakesType();
    }

    /**
     * Create an instance of {@link MaxSetPersonType }
     * 
     */
    public MaxSetPersonType createMaxSetPersonType() {
        return new MaxSetPersonType();
    }

    /**
     * Create an instance of {@link ReferenceAttestType }
     * 
     */
    public ReferenceAttestType createReferenceAttestType() {
        return new ReferenceAttestType();
    }

    /**
     * Create an instance of {@link ActiveSubstanceQuantityType }
     * 
     */
    public ActiveSubstanceQuantityType createActiveSubstanceQuantityType() {
        return new ActiveSubstanceQuantityType();
    }

    /**
     * Create an instance of {@link BvacDoctor }
     * 
     */
    public BvacDoctor createBvacDoctor() {
        return new BvacDoctor();
    }

    /**
     * Create an instance of {@link ReferenceMagistralCertificateType }
     * 
     */
    public ReferenceMagistralCertificateType createReferenceMagistralCertificateType() {
        return new ReferenceMagistralCertificateType();
    }

    /**
     * Create an instance of {@link MinSetProductType.Dispensation }
     * 
     */
    public MinSetProductType.Dispensation createMinSetProductTypeDispensation() {
        return new MinSetProductType.Dispensation();
    }

    /**
     * Create an instance of {@link TargetType }
     * 
     */
    public TargetType createTargetType() {
        return new TargetType();
    }

    /**
     * Create an instance of {@link MaxSetProductType.Motivation }
     * 
     */
    public MaxSetProductType.Motivation createMaxSetProductTypeMotivation() {
        return new MaxSetProductType.Motivation();
    }

    /**
     * Create an instance of {@link ReferencePersonType }
     * 
     */
    public ReferencePersonType createReferencePersonType() {
        return new ReferencePersonType();
    }

    /**
     * Create an instance of {@link ProductBvac }
     * 
     */
    public ProductBvac createProductBvac() {
        return new ProductBvac();
    }

    /**
     * Create an instance of {@link FormularyReferenceType }
     * 
     */
    public FormularyReferenceType createFormularyReferenceType() {
        return new FormularyReferenceType();
    }

    /**
     * Create an instance of {@link AttestType }
     * 
     */
    public AttestType createAttestType() {
        return new AttestType();
    }

    /**
     * Create an instance of {@link AdministrationInstructionsFrequencyType }
     * 
     */
    public AdministrationInstructionsFrequencyType createAdministrationInstructionsFrequencyType() {
        return new AdministrationInstructionsFrequencyType();
    }

    /**
     * Create an instance of {@link MaxSetCareProviderType }
     * 
     */
    public MaxSetCareProviderType createMaxSetCareProviderType() {
        return new MaxSetCareProviderType();
    }

    /**
     * Create an instance of {@link BvacList }
     * 
     */
    public BvacList createBvacList() {
        return new BvacList();
    }

    /**
     * Create an instance of {@link MagistralPreparationType }
     * 
     */
    public MagistralPreparationType createMagistralPreparationType() {
        return new MagistralPreparationType();
    }

    /**
     * Create an instance of {@link OriginatorType }
     * 
     */
    public OriginatorType createOriginatorType() {
        return new OriginatorType();
    }

    /**
     * Create an instance of {@link DeliveredMedicationHumanType }
     * 
     */
    public DeliveredMedicationHumanType createDeliveredMedicationHumanType() {
        return new DeliveredMedicationHumanType();
    }

    /**
     * Create an instance of {@link CompoundType }
     * 
     */
    public CompoundType createCompoundType() {
        return new CompoundType();
    }

    /**
     * Create an instance of {@link MedicationConsumerAnimalOwnerType }
     * 
     */
    public MedicationConsumerAnimalOwnerType createMedicationConsumerAnimalOwnerType() {
        return new MedicationConsumerAnimalOwnerType();
    }

    /**
     * Create an instance of {@link ReferenceMedicinalProductType }
     * 
     */
    public ReferenceMedicinalProductType createReferenceMedicinalProductType() {
        return new ReferenceMedicinalProductType();
    }

    /**
     * Create an instance of {@link Pharmacy }
     * 
     */
    public Pharmacy createPharmacy() {
        return new Pharmacy();
    }

    /**
     * Create an instance of {@link MinSetPatient }
     * 
     */
    public MinSetPatient createMinSetPatient() {
        return new MinSetPatient();
    }

    /**
     * Create an instance of {@link IdentificationBvacProduct }
     * 
     */
    public IdentificationBvacProduct createIdentificationBvacProduct() {
        return new IdentificationBvacProduct();
    }

    /**
     * Create an instance of {@link EncryptedContentType }
     * 
     */
    public EncryptedContentType createEncryptedContentType() {
        return new EncryptedContentType();
    }

    /**
     * Create an instance of {@link TotalAmounts }
     * 
     */
    public TotalAmounts createTotalAmounts() {
        return new TotalAmounts();
    }

    /**
     * Create an instance of {@link HistoryProductType }
     * 
     */
    public HistoryProductType createHistoryProductType() {
        return new HistoryProductType();
    }

    /**
     * Create an instance of {@link ReferencePharmacyType }
     * 
     */
    public ReferencePharmacyType createReferencePharmacyType() {
        return new ReferencePharmacyType();
    }

    /**
     * Create an instance of {@link AmountsBvacProduct }
     * 
     */
    public AmountsBvacProduct createAmountsBvacProduct() {
        return new AmountsBvacProduct();
    }

    /**
     * Create an instance of {@link GalenicformType }
     * 
     */
    public GalenicformType createGalenicformType() {
        return new GalenicformType();
    }

    /**
     * Create an instance of {@link CompoundType.Substance }
     * 
     */
    public CompoundType.Substance createCompoundTypeSubstance() {
        return new CompoundType.Substance();
    }

    /**
     * Create an instance of {@link SubjectReferenceType }
     * 
     */
    public SubjectReferenceType createSubjectReferenceType() {
        return new SubjectReferenceType();
    }

    /**
     * Create an instance of {@link MedicationConsumerPatientGroupType }
     * 
     */
    public MedicationConsumerPatientGroupType createMedicationConsumerPatientGroupType() {
        return new MedicationConsumerPatientGroupType();
    }

    /**
     * Create an instance of {@link MaxSetPatient.Physiology.Condition.Female.Pregnant }
     * 
     */
    public MaxSetPatient.Physiology.Condition.Female.Pregnant createMaxSetPatientPhysiologyConditionFemalePregnant() {
        return new MaxSetPatient.Physiology.Condition.Female.Pregnant();
    }

    /**
     * Create an instance of {@link PreparationType }
     * 
     */
    public PreparationType createPreparationType() {
        return new PreparationType();
    }

    /**
     * Create an instance of {@link DeferredPrescriptionType.OriginalPrescription }
     * 
     */
    public DeferredPrescriptionType.OriginalPrescription createDeferredPrescriptionTypeOriginalPrescription() {
        return new DeferredPrescriptionType.OriginalPrescription();
    }

    /**
     * Create an instance of {@link MagistralType }
     * 
     */
    public MagistralType createMagistralType() {
        return new MagistralType();
    }

    /**
     * Create an instance of {@link RecipeLineType }
     * 
     */
    public RecipeLineType createRecipeLineType() {
        return new RecipeLineType();
    }

    /**
     * Create an instance of {@link DrugRelatedProblemType }
     * 
     */
    public DrugRelatedProblemType createDrugRelatedProblemType() {
        return new DrugRelatedProblemType();
    }

    /**
     * Create an instance of {@link GenericExternalReference }
     * 
     */
    public GenericExternalReference createGenericExternalReference() {
        return new GenericExternalReference();
    }

    /**
     * Create an instance of {@link PosologyType }
     * 
     */
    public PosologyType createPosologyType() {
        return new PosologyType();
    }

    /**
     * Create an instance of {@link GenericTelecomType }
     * 
     */
    public GenericTelecomType createGenericTelecomType() {
        return new GenericTelecomType();
    }

    /**
     * Create an instance of {@link MedicationHistoryType }
     * 
     */
    public MedicationHistoryType createMedicationHistoryType() {
        return new MedicationHistoryType();
    }

    /**
     * Create an instance of {@link IdentityBvac }
     * 
     */
    public IdentityBvac createIdentityBvac() {
        return new IdentityBvac();
    }

    /**
     * Create an instance of {@link AdministrationType.Site }
     * 
     */
    public AdministrationType.Site createAdministrationTypeSite() {
        return new AdministrationType.Site();
    }

    /**
     * Create an instance of {@link MaxSetPatient.Physiology }
     * 
     */
    public MaxSetPatient.Physiology createMaxSetPatientPhysiology() {
        return new MaxSetPatient.Physiology();
    }

    /**
     * Create an instance of {@link ReferenceCareServiceType }
     * 
     */
    public ReferenceCareServiceType createReferenceCareServiceType() {
        return new ReferenceCareServiceType();
    }

    /**
     * Create an instance of {@link SpecialPrescriptionType }
     * 
     */
    public SpecialPrescriptionType createSpecialPrescriptionType() {
        return new SpecialPrescriptionType();
    }

    /**
     * Create an instance of {@link ReferencePrescriptionType }
     * 
     */
    public ReferencePrescriptionType createReferencePrescriptionType() {
        return new ReferencePrescriptionType();
    }

    /**
     * Create an instance of {@link BvacDocument }
     * 
     */
    public BvacDocument createBvacDocument() {
        return new BvacDocument();
    }

    /**
     * Create an instance of {@link SubstanceProductType }
     * 
     */
    public SubstanceProductType createSubstanceProductType() {
        return new SubstanceProductType();
    }

    /**
     * Create an instance of {@link MedicationConsumerUrgentieTrousseType }
     * 
     */
    public MedicationConsumerUrgentieTrousseType createMedicationConsumerUrgentieTrousseType() {
        return new MedicationConsumerUrgentieTrousseType();
    }

    /**
     * Create an instance of {@link MaxSetPatient.Physiology.Condition }
     * 
     */
    public MaxSetPatient.Physiology.Condition createMaxSetPatientPhysiologyCondition() {
        return new MaxSetPatient.Physiology.Condition();
    }

    /**
     * Create an instance of {@link PreparationSubstanceType }
     * 
     */
    public PreparationSubstanceType createPreparationSubstanceType() {
        return new PreparationSubstanceType();
    }

    /**
     * Create an instance of {@link DeferredPrescriptionType }
     * 
     */
    public DeferredPrescriptionType createDeferredPrescriptionType() {
        return new DeferredPrescriptionType();
    }

    /**
     * Create an instance of {@link MessageInformation }
     * 
     */
    public MessageInformation createMessageInformation() {
        return new MessageInformation();
    }

    /**
     * Create an instance of {@link BvacPatient }
     * 
     */
    public BvacPatient createBvacPatient() {
        return new BvacPatient();
    }

    /**
     * Create an instance of {@link RegimenType }
     * 
     */
    public RegimenType createRegimenType() {
        return new RegimenType();
    }

    /**
     * Create an instance of {@link IdentificationBvacNhid }
     * 
     */
    public IdentificationBvacNhid createIdentificationBvacNhid() {
        return new IdentificationBvacNhid();
    }

    /**
     * Create an instance of {@link IdentificationBvacDocument }
     * 
     */
    public IdentificationBvacDocument createIdentificationBvacDocument() {
        return new IdentificationBvacDocument();
    }

    /**
     * Create an instance of {@link MaxSetPatient.Contact }
     * 
     */
    public MaxSetPatient.Contact createMaxSetPatientContact() {
        return new MaxSetPatient.Contact();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferencePharmacyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "refPharmacy", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Pharmacy")
    public JAXBElement<ReferencePharmacyType> createRefPharmacy(ReferencePharmacyType value) {
        return new JAXBElement<ReferencePharmacyType>(_RefPharmacy_QNAME, ReferencePharmacyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "dataLocation", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-DataLocation")
    public JAXBElement<DataLocationType> createDataLocation(DataLocationType value) {
        return new JAXBElement<DataLocationType>(_DataLocation_QNAME, DataLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractMagistralCertificateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "refMagistralCertificate", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-MagistralCertificate")
    public JAXBElement<AbstractMagistralCertificateType> createRefMagistralCertificate(AbstractMagistralCertificateType value) {
        return new JAXBElement<AbstractMagistralCertificateType>(_RefMagistralCertificate_QNAME, AbstractMagistralCertificateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaxSetContactPersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "contactPerson")
    public JAXBElement<MaxSetContactPersonType> createContactPerson(MaxSetContactPersonType value) {
        return new JAXBElement<MaxSetContactPersonType>(_ContactPerson_QNAME, MaxSetContactPersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractTelecomType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Telecom")
    public JAXBElement<AbstractTelecomType> createAbstractTelecom(AbstractTelecomType value) {
        return new JAXBElement<AbstractTelecomType>(_AbstractTelecom_QNAME, AbstractTelecomType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientPrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "patientPrescription", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-HumanPrescription")
    public JAXBElement<PatientPrescriptionType> createPatientPrescription(PatientPrescriptionType value) {
        return new JAXBElement<PatientPrescriptionType>(_PatientPrescription_QNAME, PatientPrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractHumanPrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-HumanPrescription")
    public JAXBElement<AbstractHumanPrescriptionType> createAbstractHumanPrescription(AbstractHumanPrescriptionType value) {
        return new JAXBElement<AbstractHumanPrescriptionType>(_AbstractHumanPrescription_QNAME, AbstractHumanPrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Address")
    public JAXBElement<AbstractAddressType> createAbstractAddress(AbstractAddressType value) {
        return new JAXBElement<AbstractAddressType>(_AbstractAddress_QNAME, AbstractAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MedicationConsumerAnimalOwnerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "medicationConsumerAnimalOwner", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-MedicationConsumer")
    public JAXBElement<MedicationConsumerAnimalOwnerType> createMedicationConsumerAnimalOwner(MedicationConsumerAnimalOwnerType value) {
        return new JAXBElement<MedicationConsumerAnimalOwnerType>(_MedicationConsumerAnimalOwner_QNAME, MedicationConsumerAnimalOwnerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveredMedicationHumanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "deliveredMedicationHuman", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-DeliveredMedication")
    public JAXBElement<DeliveredMedicationHumanType> createDeliveredMedicationHuman(DeliveredMedicationHumanType value) {
        return new JAXBElement<DeliveredMedicationHumanType>(_DeliveredMedicationHuman_QNAME, DeliveredMedicationHumanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferencePrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "refPrescription", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Prescription")
    public JAXBElement<ReferencePrescriptionType> createRefPrescription(ReferencePrescriptionType value) {
        return new JAXBElement<ReferencePrescriptionType>(_RefPrescription_QNAME, ReferencePrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaxSetPatient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "max-Patient", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Patient")
    public JAXBElement<MaxSetPatient> createMaxPatient(MaxSetPatient value) {
        return new JAXBElement<MaxSetPatient>(_MaxPatient_QNAME, MaxSetPatient.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPharmacistType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Pharmacist")
    public JAXBElement<AbstractPharmacistType> createAbstractPharmacist(AbstractPharmacistType value) {
        return new JAXBElement<AbstractPharmacistType>(_AbstractPharmacist_QNAME, AbstractPharmacistType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Person")
    public JAXBElement<AbstractPersonType> createAbstractPerson(AbstractPersonType value) {
        return new JAXBElement<AbstractPersonType>(_AbstractPerson_QNAME, AbstractPersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MagistralCertificateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "magistralCertificate", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-MagistralCertificate")
    public JAXBElement<MagistralCertificateType> createMagistralCertificate(MagistralCertificateType value) {
        return new JAXBElement<MagistralCertificateType>(_MagistralCertificate_QNAME, MagistralCertificateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MedicationConsumerPatientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "medicationConsumerPatient", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-MedicationConsumer")
    public JAXBElement<MedicationConsumerPatientType> createMedicationConsumerPatient(MedicationConsumerPatientType value) {
        return new JAXBElement<MedicationConsumerPatientType>(_MedicationConsumerPatient_QNAME, MedicationConsumerPatientType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaxSetPersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "identification", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Person")
    public JAXBElement<MaxSetPersonType> createIdentification(MaxSetPersonType value) {
        return new JAXBElement<MaxSetPersonType>(_Identification_QNAME, MaxSetPersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegimenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "regimen", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Regimen")
    public JAXBElement<RegimenType> createRegimen(RegimenType value) {
        return new JAXBElement<RegimenType>(_Regimen_QNAME, RegimenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MedicinalProduct }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "medicinalProduct", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-MedicinalProduct")
    public JAXBElement<MedicinalProduct> createMedicinalProduct(MedicinalProduct value) {
        return new JAXBElement<MedicinalProduct>(_MedicinalProduct_QNAME, MedicinalProduct.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractVeterinaryPrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-VeterinaryPrescription")
    public JAXBElement<AbstractVeterinaryPrescriptionType> createAbstractVeterinaryPrescription(AbstractVeterinaryPrescriptionType value) {
        return new JAXBElement<AbstractVeterinaryPrescriptionType>(_AbstractVeterinaryPrescription_QNAME, AbstractVeterinaryPrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VeterinaryPrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "veterinaryPrescription", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-VeterinaryPrescription")
    public JAXBElement<VeterinaryPrescriptionType> createVeterinaryPrescription(VeterinaryPrescriptionType value) {
        return new JAXBElement<VeterinaryPrescriptionType>(_VeterinaryPrescription_QNAME, VeterinaryPrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractSupplierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Supplier")
    public JAXBElement<AbstractSupplierType> createAbstractSupplier(AbstractSupplierType value) {
        return new JAXBElement<AbstractSupplierType>(_AbstractSupplier_QNAME, AbstractSupplierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeferredPrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "deferredPrescription", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-HumanPrescription")
    public JAXBElement<DeferredPrescriptionType> createDeferredPrescription(DeferredPrescriptionType value) {
        return new JAXBElement<DeferredPrescriptionType>(_DeferredPrescription_QNAME, DeferredPrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PosologyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "posology", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Posology")
    public JAXBElement<PosologyType> createPosology(PosologyType value) {
        return new JAXBElement<PosologyType>(_Posology_QNAME, PosologyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractRawMaterialType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-RawMaterial")
    public JAXBElement<AbstractRawMaterialType> createAbstractRawMaterial(AbstractRawMaterialType value) {
        return new JAXBElement<AbstractRawMaterialType>(_AbstractRawMaterial_QNAME, AbstractRawMaterialType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RawMaterialType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "rawMaterial", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-RawMaterial")
    public JAXBElement<RawMaterialType> createRawMaterial(RawMaterialType value) {
        return new JAXBElement<RawMaterialType>(_RawMaterial_QNAME, RawMaterialType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecipeLineType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "recipeLine", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-RecipeLine")
    public JAXBElement<RecipeLineType> createRecipeLine(RecipeLineType value) {
        return new JAXBElement<RecipeLineType>(_RecipeLine_QNAME, RecipeLineType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractDataLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-DataLocation")
    public JAXBElement<AbstractDataLocationType> createAbstractDataLocation(AbstractDataLocationType value) {
        return new JAXBElement<AbstractDataLocationType>(_AbstractDataLocation_QNAME, AbstractDataLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MedicationHistoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "medicationHistoryEntity", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-DeliveredMedication")
    public JAXBElement<MedicationHistoryType> createMedicationHistoryEntity(MedicationHistoryType value) {
        return new JAXBElement<MedicationHistoryType>(_MedicationHistoryEntity_QNAME, MedicationHistoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubstanceProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "substanceProduct", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-SubstanceProduct")
    public JAXBElement<SubstanceProductType> createSubstanceProduct(SubstanceProductType value) {
        return new JAXBElement<SubstanceProductType>(_SubstanceProduct_QNAME, SubstanceProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractMedicationConsumerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-MedicationConsumer")
    public JAXBElement<AbstractMedicationConsumerType> createAbstractMedicationConsumer(AbstractMedicationConsumerType value) {
        return new JAXBElement<AbstractMedicationConsumerType>(_AbstractMedicationConsumer_QNAME, AbstractMedicationConsumerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KmehrPrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "kmehrPrescription", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Prescription")
    public JAXBElement<KmehrPrescriptionType> createKmehrPrescription(KmehrPrescriptionType value) {
        return new JAXBElement<KmehrPrescriptionType>(_KmehrPrescription_QNAME, KmehrPrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "statusMessage", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-StatusMessage")
    public JAXBElement<StatusMessageType> createStatusMessage(StatusMessageType value) {
        return new JAXBElement<StatusMessageType>(_StatusMessage_QNAME, StatusMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractCareServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-CareService")
    public JAXBElement<AbstractCareServiceType> createAbstractCareService(AbstractCareServiceType value) {
        return new JAXBElement<AbstractCareServiceType>(_AbstractCareService_QNAME, AbstractCareServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractRecipeLineType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-RecipeLine")
    public JAXBElement<AbstractRecipeLineType> createAbstractRecipeLine(AbstractRecipeLineType value) {
        return new JAXBElement<AbstractRecipeLineType>(_AbstractRecipeLine_QNAME, AbstractRecipeLineType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractStatusMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-StatusMessage")
    public JAXBElement<AbstractStatusMessageType> createAbstractStatusMessage(AbstractStatusMessageType value) {
        return new JAXBElement<AbstractStatusMessageType>(_AbstractStatusMessage_QNAME, AbstractStatusMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MedicationConsumerUrgentieTrousseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "medicationConsumerUrgentieTrousse", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-MedicationConsumer")
    public JAXBElement<MedicationConsumerUrgentieTrousseType> createMedicationConsumerUrgentieTrousse(MedicationConsumerUrgentieTrousseType value) {
        return new JAXBElement<MedicationConsumerUrgentieTrousseType>(_MedicationConsumerUrgentieTrousse_QNAME, MedicationConsumerUrgentieTrousseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PreparationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "preparation", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Preparation")
    public JAXBElement<PreparationType> createPreparation(PreparationType value) {
        return new JAXBElement<PreparationType>(_Preparation_QNAME, PreparationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractMedicinalProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-MedicinalProduct")
    public JAXBElement<AbstractMedicinalProductType> createAbstractMedicinalProduct(AbstractMedicinalProductType value) {
        return new JAXBElement<AbstractMedicinalProductType>(_AbstractMedicinalProduct_QNAME, AbstractMedicinalProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractSubstanceProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-SubstanceProduct")
    public JAXBElement<AbstractSubstanceProductType> createAbstractSubstanceProduct(AbstractSubstanceProductType value) {
        return new JAXBElement<AbstractSubstanceProductType>(_AbstractSubstanceProduct_QNAME, AbstractSubstanceProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPharmacyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Pharmacy")
    public JAXBElement<AbstractPharmacyType> createAbstractPharmacy(AbstractPharmacyType value) {
        return new JAXBElement<AbstractPharmacyType>(_AbstractPharmacy_QNAME, AbstractPharmacyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractCareProviderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-CareProvider")
    public JAXBElement<AbstractCareProviderType> createAbstractCareProvider(AbstractCareProviderType value) {
        return new JAXBElement<AbstractCareProviderType>(_AbstractCareProvider_QNAME, AbstractCareProviderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPatientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Patient")
    public JAXBElement<AbstractPatientType> createAbstractPatient(AbstractPatientType value) {
        return new JAXBElement<AbstractPatientType>(_AbstractPatient_QNAME, AbstractPatientType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "person", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Person")
    public JAXBElement<PersonType> createPerson(PersonType value) {
        return new JAXBElement<PersonType>(_Person_QNAME, PersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractMagistralCertificateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-MagistralCertificate")
    public JAXBElement<AbstractMagistralCertificateType> createAbstractMagistralCertificate(AbstractMagistralCertificateType value) {
        return new JAXBElement<AbstractMagistralCertificateType>(_AbstractMagistralCertificate_QNAME, AbstractMagistralCertificateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferencePersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "refPerson", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Person")
    public JAXBElement<ReferencePersonType> createRefPerson(ReferencePersonType value) {
        return new JAXBElement<ReferencePersonType>(_RefPerson_QNAME, ReferencePersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPreparationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Preparation")
    public JAXBElement<AbstractPreparationType> createAbstractPreparation(AbstractPreparationType value) {
        return new JAXBElement<AbstractPreparationType>(_AbstractPreparation_QNAME, AbstractPreparationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MinSetPatient }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "min-Patient", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Patient")
    public JAXBElement<MinSetPatient> createMinPatient(MinSetPatient value) {
        return new JAXBElement<MinSetPatient>(_MinPatient_QNAME, MinSetPatient.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPosologyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Posology")
    public JAXBElement<AbstractPosologyType> createAbstractPosology(AbstractPosologyType value) {
        return new JAXBElement<AbstractPosologyType>(_AbstractPosology_QNAME, AbstractPosologyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecialPrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "specialPrescription", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-HumanPrescription")
    public JAXBElement<SpecialPrescriptionType> createSpecialPrescription(SpecialPrescriptionType value) {
        return new JAXBElement<SpecialPrescriptionType>(_SpecialPrescription_QNAME, SpecialPrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPrescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Prescription")
    public JAXBElement<AbstractPrescriptionType> createAbstractPrescription(AbstractPrescriptionType value) {
        return new JAXBElement<AbstractPrescriptionType>(_AbstractPrescription_QNAME, AbstractPrescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractDeliveredMedicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-DeliveredMedication")
    public JAXBElement<AbstractDeliveredMedicationType> createAbstractDeliveredMedication(AbstractDeliveredMedicationType value) {
        return new JAXBElement<AbstractDeliveredMedicationType>(_AbstractDeliveredMedication_QNAME, AbstractDeliveredMedicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MedicationConsumerPatientGroupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "medicationConsumerPatientGroup", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-MedicationConsumer")
    public JAXBElement<MedicationConsumerPatientGroupType> createMedicationConsumerPatientGroup(MedicationConsumerPatientGroupType value) {
        return new JAXBElement<MedicationConsumerPatientGroupType>(_MedicationConsumerPatientGroup_QNAME, MedicationConsumerPatientGroupType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceAttestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "refAttest", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Attest")
    public JAXBElement<ReferenceAttestType> createRefAttest(ReferenceAttestType value) {
        return new JAXBElement<ReferenceAttestType>(_RefAttest_QNAME, ReferenceAttestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractEntityType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Entity")
    public JAXBElement<AbstractEntityType> createAbstractEntity(AbstractEntityType value) {
        return new JAXBElement<AbstractEntityType>(_AbstractEntity_QNAME, AbstractEntityType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncomingMedicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "incomingMedication", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-IncomingMedication")
    public JAXBElement<IncomingMedicationType> createIncomingMedication(IncomingMedicationType value) {
        return new JAXBElement<IncomingMedicationType>(_IncomingMedication_QNAME, IncomingMedicationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractAttestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Attest")
    public JAXBElement<AbstractAttestType> createAbstractAttest(AbstractAttestType value) {
        return new JAXBElement<AbstractAttestType>(_AbstractAttest_QNAME, AbstractAttestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceCareServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "refCareService", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-CareService")
    public JAXBElement<ReferenceCareServiceType> createRefCareService(ReferenceCareServiceType value) {
        return new JAXBElement<ReferenceCareServiceType>(_RefCareService_QNAME, ReferenceCareServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MaxSetCareProviderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "hcparty", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-CareProvider")
    public JAXBElement<MaxSetCareProviderType> createHcparty(MaxSetCareProviderType value) {
        return new JAXBElement<MaxSetCareProviderType>(_Hcparty_QNAME, MaxSetCareProviderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractRegimenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-Regimen")
    public JAXBElement<AbstractRegimenType> createAbstractRegimen(AbstractRegimenType value) {
        return new JAXBElement<AbstractRegimenType>(_AbstractRegimen_QNAME, AbstractRegimenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceMedicinalProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "refMedicinalProduct", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-MedicinalProduct")
    public JAXBElement<ReferenceMedicinalProductType> createRefMedicinalProduct(ReferenceMedicinalProductType value) {
        return new JAXBElement<ReferenceMedicinalProductType>(_RefMedicinalProduct_QNAME, ReferenceMedicinalProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "attest", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-Attest")
    public JAXBElement<AttestType> createAttest(AttestType value) {
        return new JAXBElement<AttestType>(_Attest_QNAME, AttestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveredMedicationVeterinairType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "deliveredMedicationVeterinair", substitutionHeadNamespace = "http://www.apb.be/standards/smoa/schema/model/v1", substitutionHeadName = "abstract-DeliveredMedication")
    public JAXBElement<DeliveredMedicationVeterinairType> createDeliveredMedicationVeterinair(DeliveredMedicationVeterinairType value) {
        return new JAXBElement<DeliveredMedicationVeterinairType>(_DeliveredMedicationVeterinair_QNAME, DeliveredMedicationVeterinairType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractIncomingMedicationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", name = "abstract-IncomingMedication")
    public JAXBElement<AbstractIncomingMedicationType> createAbstractIncomingMedication(AbstractIncomingMedicationType value) {
        return new JAXBElement<AbstractIncomingMedicationType>(_AbstractIncomingMedication_QNAME, AbstractIncomingMedicationType.class, null, value);
    }

}
