//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import be.apb.standards.smoa.schema.code.v1.AbstractCountryCodeType;
import be.apb.standards.smoa.schema.code.v1.AbstractProfessionCodeType;
import be.apb.standards.smoa.schema.code.v1.AbstractSexCodeType;
import be.apb.standards.smoa.schema.id.v1.AbstractPersonIdType;


/**
 * <p>Java class for PersonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.apb.be/standards/smoa/schema/model/v1}AbstractPersonType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.apb.be/standards/smoa/schema/id/v1}Abstract-PersonIdType"/>
 *         &lt;element name="firstNames">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="firstName" type="{http://www.apb.be/standards/smoa/schema/v1}PersonFirstNameType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="familyName" type="{http://www.apb.be/standards/smoa/schema/v1}PersonNameType"/>
 *         &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="deathdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="sex" type="{http://www.apb.be/standards/smoa/schema/code/v1}Abstract-SexCodeType"/>
 *         &lt;element name="nationality" type="{http://www.apb.be/standards/smoa/schema/code/v1}Abstract-CountryCodeType" minOccurs="0"/>
 *         &lt;group ref="{http://www.apb.be/standards/smoa/schema/model/v1}contactInformation"/>
 *         &lt;element name="usuallanguage" type="{http://www.w3.org/2001/XMLSchema}language" minOccurs="0"/>
 *         &lt;element name="profession" type="{http://www.apb.be/standards/smoa/schema/code/v1}Abstract-ProfessionCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonType", propOrder = {
    "id",
    "firstNames",
    "familyName",
    "birthDate",
    "deathdate",
    "sex",
    "nationality",
    "address",
    "telecom",
    "usuallanguage",
    "profession"
})
public class PersonType
    extends AbstractPersonType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected AbstractPersonIdType id;
    @XmlElement(required = true)
    protected PersonType.FirstNames firstNames;
    @XmlElement(required = true)
    protected String familyName;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deathdate;
    @XmlElement(required = true)
    protected AbstractSexCodeType sex;
    protected AbstractCountryCodeType nationality;
    protected List<AbstractAddressType> address;
    protected List<AbstractTelecomType> telecom;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String usuallanguage;
    protected AbstractProfessionCodeType profession;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractPersonIdType }
     *     
     */
    public AbstractPersonIdType getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractPersonIdType }
     *     
     */
    public void setId(AbstractPersonIdType value) {
        this.id = value;
    }

    /**
     * Gets the value of the firstNames property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType.FirstNames }
     *     
     */
    public PersonType.FirstNames getFirstNames() {
        return firstNames;
    }

    /**
     * Sets the value of the firstNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType.FirstNames }
     *     
     */
    public void setFirstNames(PersonType.FirstNames value) {
        this.firstNames = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the deathdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeathdate() {
        return deathdate;
    }

    /**
     * Sets the value of the deathdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeathdate(XMLGregorianCalendar value) {
        this.deathdate = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractSexCodeType }
     *     
     */
    public AbstractSexCodeType getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractSexCodeType }
     *     
     */
    public void setSex(AbstractSexCodeType value) {
        this.sex = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractCountryCodeType }
     *     
     */
    public AbstractCountryCodeType getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractCountryCodeType }
     *     
     */
    public void setNationality(AbstractCountryCodeType value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractAddressType }
     * 
     * 
     */
    public List<AbstractAddressType> getAddress() {
        if (address == null) {
            address = new ArrayList<AbstractAddressType>();
        }
        return this.address;
    }

    /**
     * Gets the value of the telecom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telecom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelecom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractTelecomType }
     * 
     * 
     */
    public List<AbstractTelecomType> getTelecom() {
        if (telecom == null) {
            telecom = new ArrayList<AbstractTelecomType>();
        }
        return this.telecom;
    }

    /**
     * Gets the value of the usuallanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuallanguage() {
        return usuallanguage;
    }

    /**
     * Sets the value of the usuallanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuallanguage(String value) {
        this.usuallanguage = value;
    }

    /**
     * Gets the value of the profession property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractProfessionCodeType }
     *     
     */
    public AbstractProfessionCodeType getProfession() {
        return profession;
    }

    /**
     * Sets the value of the profession property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractProfessionCodeType }
     *     
     */
    public void setProfession(AbstractProfessionCodeType value) {
        this.profession = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="firstName" type="{http://www.apb.be/standards/smoa/schema/v1}PersonFirstNameType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firstName"
    })
    public static class FirstNames
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<String> firstName;

        /**
         * Gets the value of the firstName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the firstName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFirstName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getFirstName() {
            if (firstName == null) {
                firstName = new ArrayList<String>();
            }
            return this.firstName;
        }

    }

}
