//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import be.apb.standards.smoa.schema.code.v1.AbstractAdministrationUnitValuesCodeType;


/**
 * quantity of product and frequence of administration per unit of period of time (day, week, hour, month etc...)
 * 
 * <p>Java class for PosologyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PosologyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.apb.be/standards/smoa/schema/model/v1}AbstractPosologyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="low" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *           &lt;element name="high" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *           &lt;element name="unit" type="{http://www.apb.be/standards/smoa/schema/code/v1}Abstract-AdministrationUnitValuesCodeType"/>
 *           &lt;element name="takes" type="{http://www.apb.be/standards/smoa/schema/model/v1}PosologyTakesType"/>
 *         &lt;/sequence>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PosologyType", propOrder = {
    "low",
    "high",
    "unit",
    "takes",
    "text"
})
public class PosologyType
    extends AbstractPosologyType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected BigDecimal low;
    protected BigDecimal high;
    protected AbstractAdministrationUnitValuesCodeType unit;
    protected PosologyTakesType takes;
    protected String text;

    /**
     * Gets the value of the low property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLow() {
        return low;
    }

    /**
     * Sets the value of the low property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLow(BigDecimal value) {
        this.low = value;
    }

    /**
     * Gets the value of the high property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHigh() {
        return high;
    }

    /**
     * Sets the value of the high property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHigh(BigDecimal value) {
        this.high = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractAdministrationUnitValuesCodeType }
     *     
     */
    public AbstractAdministrationUnitValuesCodeType getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractAdministrationUnitValuesCodeType }
     *     
     */
    public void setUnit(AbstractAdministrationUnitValuesCodeType value) {
        this.unit = value;
    }

    /**
     * Gets the value of the takes property.
     * 
     * @return
     *     possible object is
     *     {@link PosologyTakesType }
     *     
     */
    public PosologyTakesType getTakes() {
        return takes;
    }

    /**
     * Sets the value of the takes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PosologyTakesType }
     *     
     */
    public void setTakes(PosologyTakesType value) {
        this.takes = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
