//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import be.apb.standards.smoa.schema.v1.QuantityType;


/**
 * <p>Java class for PreparationSubstanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreparationSubstanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.apb.be/standards/smoa/schema/model/v1}abstract-RawMaterial"/>
 *         &lt;element name="dose" type="{http://www.apb.be/standards/smoa/schema/v1}QuantityType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreparationSubstanceType", propOrder = {
    "abstractRawMaterial",
    "dose"
})
public class PreparationSubstanceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "abstract-RawMaterial", namespace = "http://www.apb.be/standards/smoa/schema/model/v1", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractRawMaterialType> abstractRawMaterial;
    @XmlElement(required = true)
    protected QuantityType dose;

    /**
     * Gets the value of the abstractRawMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AbstractRawMaterialType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RawMaterialType }{@code >}
     *     
     */
    public JAXBElement<? extends AbstractRawMaterialType> getAbstractRawMaterial() {
        return abstractRawMaterial;
    }

    /**
     * Sets the value of the abstractRawMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AbstractRawMaterialType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RawMaterialType }{@code >}
     *     
     */
    public void setAbstractRawMaterial(JAXBElement<? extends AbstractRawMaterialType> value) {
        this.abstractRawMaterial = ((JAXBElement<? extends AbstractRawMaterialType> ) value);
    }

    /**
     * Gets the value of the dose property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityType }
     *     
     */
    public QuantityType getDose() {
        return dose;
    }

    /**
     * Sets the value of the dose property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityType }
     *     
     */
    public void setDose(QuantityType value) {
        this.dose = value;
    }

}
