//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import be.apb.standards.smoa.schema.id.v1.AbstractMedicinalProductIdType;


/**
 * <p>Java class for ReferenceMedicinalProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceMedicinalProductType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.apb.be/standards/smoa/schema/model/v1}AbstractMedicinalProductType">
 *       &lt;sequence>
 *         &lt;element name="medicinalProductId" type="{http://www.apb.be/standards/smoa/schema/id/v1}Abstract-MedicinalProductIdType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceMedicinalProductType", propOrder = {
    "medicinalProductId"
})
public class ReferenceMedicinalProductType
    extends AbstractMedicinalProductType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected AbstractMedicinalProductIdType medicinalProductId;

    /**
     * Gets the value of the medicinalProductId property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractMedicinalProductIdType }
     *     
     */
    public AbstractMedicinalProductIdType getMedicinalProductId() {
        return medicinalProductId;
    }

    /**
     * Sets the value of the medicinalProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractMedicinalProductIdType }
     *     
     */
    public void setMedicinalProductId(AbstractMedicinalProductIdType value) {
        this.medicinalProductId = value;
    }

}
