//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import be.apb.standards.smoa.schema.code.v1.AbstractDayPeriodCodeType;


/**
 * <p>Java class for RegimenDayTimeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegimenDayTimeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *           &lt;element name="dayperiod" type="{http://www.apb.be/standards/smoa/schema/code/v1}Abstract-DayPeriodCodeType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegimenDayTimeType", propOrder = {
    "time",
    "dayperiod"
})
public class RegimenDayTimeType implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar time;
    protected AbstractDayPeriodCodeType dayperiod;

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the dayperiod property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractDayPeriodCodeType }
     *     
     */
    public AbstractDayPeriodCodeType getDayperiod() {
        return dayperiod;
    }

    /**
     * Sets the value of the dayperiod property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractDayPeriodCodeType }
     *     
     */
    public void setDayperiod(AbstractDayPeriodCodeType value) {
        this.dayperiod = value;
    }

}
