//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 02:31:44 PM CET 
//


package be.apb.standards.smoa.schema.model.v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SubjectReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjectReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageGUID" type="{http://www.apb.be/standards/smoa/schema/v1}UuidType"/>
 *         &lt;element name="SessionGUID" type="{http://www.apb.be/standards/smoa/schema/v1}UuidType" minOccurs="0"/>
 *         &lt;element name="DispensationGUID" type="{http://www.apb.be/standards/smoa/schema/v1}UuidType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectReferenceType", propOrder = {
    "messageGUID",
    "sessionGUID",
    "dispensationGUID"
})
public class SubjectReferenceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "MessageGUID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String messageGUID;
    @XmlElement(name = "SessionGUID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sessionGUID;
    @XmlElement(name = "DispensationGUID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dispensationGUID;

    /**
     * Gets the value of the messageGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageGUID() {
        return messageGUID;
    }

    /**
     * Sets the value of the messageGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageGUID(String value) {
        this.messageGUID = value;
    }

    /**
     * Gets the value of the sessionGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionGUID() {
        return sessionGUID;
    }

    /**
     * Sets the value of the sessionGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionGUID(String value) {
        this.sessionGUID = value;
    }

    /**
     * Gets the value of the dispensationGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispensationGUID() {
        return dispensationGUID;
    }

    /**
     * Sets the value of the dispensationGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispensationGUID(String value) {
        this.dispensationGUID = value;
    }

}
