//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CD-SITE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CD-SITE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="BE"/>
 *     &lt;enumeration value="blood"/>
 *     &lt;enumeration value="BN"/>
 *     &lt;enumeration value="BU"/>
 *     &lt;enumeration value="CT"/>
 *     &lt;enumeration value="LA"/>
 *     &lt;enumeration value="LAC"/>
 *     &lt;enumeration value="LACF"/>
 *     &lt;enumeration value="LD"/>
 *     &lt;enumeration value="LE"/>
 *     &lt;enumeration value="LEJ"/>
 *     &lt;enumeration value="LF"/>
 *     &lt;enumeration value="LG"/>
 *     &lt;enumeration value="LH"/>
 *     &lt;enumeration value="LIJ"/>
 *     &lt;enumeration value="LLAQ"/>
 *     &lt;enumeration value="LLFA"/>
 *     &lt;enumeration value="LMFA"/>
 *     &lt;enumeration value="LN"/>
 *     &lt;enumeration value="LPC"/>
 *     &lt;enumeration value="LSC"/>
 *     &lt;enumeration value="LT"/>
 *     &lt;enumeration value="LUA"/>
 *     &lt;enumeration value="LUAQ"/>
 *     &lt;enumeration value="LUFA"/>
 *     &lt;enumeration value="LVG"/>
 *     &lt;enumeration value="LVL"/>
 *     &lt;enumeration value="NB"/>
 *     &lt;enumeration value="OD"/>
 *     &lt;enumeration value="OS"/>
 *     &lt;enumeration value="OU"/>
 *     &lt;enumeration value="PA"/>
 *     &lt;enumeration value="PERIN"/>
 *     &lt;enumeration value="RA"/>
 *     &lt;enumeration value="RAC"/>
 *     &lt;enumeration value="RACF"/>
 *     &lt;enumeration value="RD"/>
 *     &lt;enumeration value="RE"/>
 *     &lt;enumeration value="REJ"/>
 *     &lt;enumeration value="RF"/>
 *     &lt;enumeration value="RG"/>
 *     &lt;enumeration value="RH"/>
 *     &lt;enumeration value="RIJ"/>
 *     &lt;enumeration value="RLAQ"/>
 *     &lt;enumeration value="RLFA"/>
 *     &lt;enumeration value="RMFA"/>
 *     &lt;enumeration value="RN"/>
 *     &lt;enumeration value="RPC"/>
 *     &lt;enumeration value="RSC"/>
 *     &lt;enumeration value="RT"/>
 *     &lt;enumeration value="RUA"/>
 *     &lt;enumeration value="RUAQ"/>
 *     &lt;enumeration value="RUFA"/>
 *     &lt;enumeration value="RVG"/>
 *     &lt;enumeration value="RVL"/>
 *     &lt;enumeration value="lk"/>
 *     &lt;enumeration value="rk"/>
 *     &lt;enumeration value="lhip"/>
 *     &lt;enumeration value="rhip"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CD-SITE")
@XmlEnum
public enum CDSITE {

    BE("BE"),
    @XmlEnumValue("blood")
    BLOOD("blood"),
    BN("BN"),
    BU("BU"),
    CT("CT"),
    LA("LA"),
    LAC("LAC"),
    LACF("LACF"),
    LD("LD"),
    LE("LE"),
    LEJ("LEJ"),
    LF("LF"),
    LG("LG"),
    LH("LH"),
    LIJ("LIJ"),
    LLAQ("LLAQ"),
    LLFA("LLFA"),
    LMFA("LMFA"),
    LN("LN"),
    LPC("LPC"),
    LSC("LSC"),
    LT("LT"),
    LUA("LUA"),
    LUAQ("LUAQ"),
    LUFA("LUFA"),
    LVG("LVG"),
    LVL("LVL"),
    NB("NB"),
    OD("OD"),
    OS("OS"),
    OU("OU"),
    PA("PA"),
    PERIN("PERIN"),
    RA("RA"),
    RAC("RAC"),
    RACF("RACF"),
    RD("RD"),
    RE("RE"),
    REJ("REJ"),
    RF("RF"),
    RG("RG"),
    RH("RH"),
    RIJ("RIJ"),
    RLAQ("RLAQ"),
    RLFA("RLFA"),
    RMFA("RMFA"),
    RN("RN"),
    RPC("RPC"),
    RSC("RSC"),
    RT("RT"),
    RUA("RUA"),
    RUAQ("RUAQ"),
    RUFA("RUFA"),
    RVG("RVG"),
    RVL("RVL"),
    @XmlEnumValue("lk")
    LK("lk"),
    @XmlEnumValue("rk")
    RK("rk"),
    @XmlEnumValue("lhip")
    LHIP("lhip"),
    @XmlEnumValue("rhip")
    RHIP("rhip");
    private final String value;

    CDSITE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CDSITE fromValue(String v) {
        for (CDSITE c: CDSITE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
