//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 04:11:17 PM CET 
//


package be.apb.standards.smoa.schema.v1;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import be.apb.standards.smoa.schema.model.v1.AbstractEntityType;


/**
 * <p>Java class for EventFolderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventFolderType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.apb.be/standards/smoa/schema/v1}AbstractFolderType">
 *       &lt;sequence>
 *         &lt;element name="events" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="event" type="{http://www.apb.be/standards/smoa/schema/v1}AbstractEventType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="entitySpace" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entity" type="{http://www.apb.be/standards/smoa/schema/model/v1}AbstractEntityType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventFolderType", propOrder = {
    "events",
    "entitySpace"
})
public class EventFolderType
    extends AbstractFolderType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected EventFolderType.Events events;
    protected EventFolderType.EntitySpace entitySpace;

    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link EventFolderType.Events }
     *     
     */
    public EventFolderType.Events getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventFolderType.Events }
     *     
     */
    public void setEvents(EventFolderType.Events value) {
        this.events = value;
    }

    /**
     * Gets the value of the entitySpace property.
     * 
     * @return
     *     possible object is
     *     {@link EventFolderType.EntitySpace }
     *     
     */
    public EventFolderType.EntitySpace getEntitySpace() {
        return entitySpace;
    }

    /**
     * Sets the value of the entitySpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventFolderType.EntitySpace }
     *     
     */
    public void setEntitySpace(EventFolderType.EntitySpace value) {
        this.entitySpace = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entity" type="{http://www.apb.be/standards/smoa/schema/model/v1}AbstractEntityType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entity"
    })
    public static class EntitySpace
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected List<AbstractEntityType> entity;

        /**
         * Gets the value of the entity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AbstractEntityType }
         * 
         * 
         */
        public List<AbstractEntityType> getEntity() {
            if (entity == null) {
                entity = new ArrayList<AbstractEntityType>();
            }
            return this.entity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="event" type="{http://www.apb.be/standards/smoa/schema/v1}AbstractEventType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "event"
    })
    public static class Events
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected List<AbstractEventType> event;

        /**
         * Gets the value of the event property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the event property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AbstractEventType }
         * 
         * 
         */
        public List<AbstractEventType> getEvent() {
            if (event == null) {
                event = new ArrayList<AbstractEventType>();
            }
            return this.event;
        }

    }

}
