//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.v1;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import be.apb.standards.smoa.schema.id.v1.NihiiIdType;
import be.apb.standards.smoa.schema.model.v1.DrugRelatedProblemType;
import be.apb.standards.smoa.schema.model.v1.MaxSetCareProviderType;
import be.apb.standards.smoa.schema.model.v1.MaxSetPatient;
import be.apb.standards.smoa.schema.model.v1.MaxSetProductType;


/**
 * The maximal data set of a patient pharmaceutical care session. The ID is the session GUID.
 * 
 * <p>Java class for PharmaceuticalCareEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PharmaceuticalCareEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.apb.be/standards/smoa/schema/v1}AbstractEventType">
 *       &lt;sequence>
 *         &lt;element name="sessionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="pharmacyId" type="{http://www.apb.be/standards/smoa/schema/id/v1}NihiiIdType"/>
 *         &lt;element ref="{http://www.apb.be/standards/smoa/schema/model/v1}max-Patient"/>
 *         &lt;element name="dispensedForSamePrescription" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.apb.be/standards/smoa/schema/model/v1}hcparty"/>
 *                   &lt;element name="product" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.apb.be/standards/smoa/schema/model/v1}MaxSetProductType">
 *                           &lt;attribute name="onSubstanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dispensedWithoutPrescription" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="product" type="{http://www.apb.be/standards/smoa/schema/model/v1}MaxSetProductType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pharmaceuticalCareActivities" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="drugRelatedProblem" type="{http://www.apb.be/standards/smoa/schema/model/v1}DrugRelatedProblemType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="metaDataList" type="{http://www.apb.be/standards/smoa/schema/v1}MetaDataListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PharmaceuticalCareEventType", propOrder = {
    "sessionDateTime",
    "pharmacyId",
    "maxPatient",
    "dispensedForSamePrescription",
    "dispensedWithoutPrescription",
    "pharmaceuticalCareActivities",
    "metaDataList"
})
public class PharmaceuticalCareEventType
    extends AbstractEventType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sessionDateTime;
    @XmlElement(required = true)
    protected NihiiIdType pharmacyId;
    @XmlElement(name = "max-Patient", namespace = "http://www.apb.be/standards/smoa/schema/model/v1", required = true)
    protected MaxSetPatient maxPatient;
    protected List<PharmaceuticalCareEventType.DispensedForSamePrescription> dispensedForSamePrescription;
    protected PharmaceuticalCareEventType.DispensedWithoutPrescription dispensedWithoutPrescription;
    protected PharmaceuticalCareEventType.PharmaceuticalCareActivities pharmaceuticalCareActivities;
    protected MetaDataListType metaDataList;

    /**
     * Gets the value of the sessionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSessionDateTime() {
        return sessionDateTime;
    }

    /**
     * Sets the value of the sessionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSessionDateTime(XMLGregorianCalendar value) {
        this.sessionDateTime = value;
    }

    /**
     * Gets the value of the pharmacyId property.
     * 
     * @return
     *     possible object is
     *     {@link NihiiIdType }
     *     
     */
    public NihiiIdType getPharmacyId() {
        return pharmacyId;
    }

    /**
     * Sets the value of the pharmacyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link NihiiIdType }
     *     
     */
    public void setPharmacyId(NihiiIdType value) {
        this.pharmacyId = value;
    }

    /**
     * Gets the value of the maxPatient property.
     * 
     * @return
     *     possible object is
     *     {@link MaxSetPatient }
     *     
     */
    public MaxSetPatient getMaxPatient() {
        return maxPatient;
    }

    /**
     * Sets the value of the maxPatient property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxSetPatient }
     *     
     */
    public void setMaxPatient(MaxSetPatient value) {
        this.maxPatient = value;
    }

    /**
     * Gets the value of the dispensedForSamePrescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispensedForSamePrescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispensedForSamePrescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PharmaceuticalCareEventType.DispensedForSamePrescription }
     * 
     * 
     */
    public List<PharmaceuticalCareEventType.DispensedForSamePrescription> getDispensedForSamePrescription() {
        if (dispensedForSamePrescription == null) {
            dispensedForSamePrescription = new ArrayList<PharmaceuticalCareEventType.DispensedForSamePrescription>();
        }
        return this.dispensedForSamePrescription;
    }

    /**
     * Gets the value of the dispensedWithoutPrescription property.
     * 
     * @return
     *     possible object is
     *     {@link PharmaceuticalCareEventType.DispensedWithoutPrescription }
     *     
     */
    public PharmaceuticalCareEventType.DispensedWithoutPrescription getDispensedWithoutPrescription() {
        return dispensedWithoutPrescription;
    }

    /**
     * Sets the value of the dispensedWithoutPrescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link PharmaceuticalCareEventType.DispensedWithoutPrescription }
     *     
     */
    public void setDispensedWithoutPrescription(PharmaceuticalCareEventType.DispensedWithoutPrescription value) {
        this.dispensedWithoutPrescription = value;
    }

    /**
     * Gets the value of the pharmaceuticalCareActivities property.
     * 
     * @return
     *     possible object is
     *     {@link PharmaceuticalCareEventType.PharmaceuticalCareActivities }
     *     
     */
    public PharmaceuticalCareEventType.PharmaceuticalCareActivities getPharmaceuticalCareActivities() {
        return pharmaceuticalCareActivities;
    }

    /**
     * Sets the value of the pharmaceuticalCareActivities property.
     * 
     * @param value
     *     allowed object is
     *     {@link PharmaceuticalCareEventType.PharmaceuticalCareActivities }
     *     
     */
    public void setPharmaceuticalCareActivities(PharmaceuticalCareEventType.PharmaceuticalCareActivities value) {
        this.pharmaceuticalCareActivities = value;
    }

    /**
     * Gets the value of the metaDataList property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDataListType }
     *     
     */
    public MetaDataListType getMetaDataList() {
        return metaDataList;
    }

    /**
     * Sets the value of the metaDataList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDataListType }
     *     
     */
    public void setMetaDataList(MetaDataListType value) {
        this.metaDataList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.apb.be/standards/smoa/schema/model/v1}hcparty"/>
     *         &lt;element name="product" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.apb.be/standards/smoa/schema/model/v1}MaxSetProductType">
     *                 &lt;attribute name="onSubstanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hcparty",
        "product"
    })
    public static class DispensedForSamePrescription
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(namespace = "http://www.apb.be/standards/smoa/schema/model/v1", required = true)
        protected MaxSetCareProviderType hcparty;
        @XmlElement(required = true)
        protected List<PharmaceuticalCareEventType.DispensedForSamePrescription.Product> product;

        /**
         * Gets the value of the hcparty property.
         * 
         * @return
         *     possible object is
         *     {@link MaxSetCareProviderType }
         *     
         */
        public MaxSetCareProviderType getHcparty() {
            return hcparty;
        }

        /**
         * Sets the value of the hcparty property.
         * 
         * @param value
         *     allowed object is
         *     {@link MaxSetCareProviderType }
         *     
         */
        public void setHcparty(MaxSetCareProviderType value) {
            this.hcparty = value;
        }

        /**
         * Gets the value of the product property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the product property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProduct().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PharmaceuticalCareEventType.DispensedForSamePrescription.Product }
         * 
         * 
         */
        public List<PharmaceuticalCareEventType.DispensedForSamePrescription.Product> getProduct() {
            if (product == null) {
                product = new ArrayList<PharmaceuticalCareEventType.DispensedForSamePrescription.Product>();
            }
            return this.product;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.apb.be/standards/smoa/schema/model/v1}MaxSetProductType">
         *       &lt;attribute name="onSubstanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Product
            extends MaxSetProductType
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlAttribute(required = true)
            protected boolean onSubstanceName;

            /**
             * Gets the value of the onSubstanceName property.
             * 
             */
            public boolean isOnSubstanceName() {
                return onSubstanceName;
            }

            /**
             * Sets the value of the onSubstanceName property.
             * 
             */
            public void setOnSubstanceName(boolean value) {
                this.onSubstanceName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="product" type="{http://www.apb.be/standards/smoa/schema/model/v1}MaxSetProductType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "product"
    })
    public static class DispensedWithoutPrescription
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<MaxSetProductType> product;

        /**
         * Gets the value of the product property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the product property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProduct().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MaxSetProductType }
         * 
         * 
         */
        public List<MaxSetProductType> getProduct() {
            if (product == null) {
                product = new ArrayList<MaxSetProductType>();
            }
            return this.product;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="drugRelatedProblem" type="{http://www.apb.be/standards/smoa/schema/model/v1}DrugRelatedProblemType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "drugRelatedProblem"
    })
    public static class PharmaceuticalCareActivities
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<DrugRelatedProblemType> drugRelatedProblem;

        /**
         * Gets the value of the drugRelatedProblem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the drugRelatedProblem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDrugRelatedProblem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DrugRelatedProblemType }
         * 
         * 
         */
        public List<DrugRelatedProblemType> getDrugRelatedProblem() {
            if (drugRelatedProblem == null) {
                drugRelatedProblem = new ArrayList<DrugRelatedProblemType>();
            }
            return this.drugRelatedProblem;
        }

    }

}
