//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuantityPrefix.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QuantityPrefix">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ana"/>
 *     &lt;enumeration value="ana ad"/>
 *     &lt;enumeration value="ad"/>
 *     &lt;enumeration value="qs"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QuantityPrefix")
@XmlEnum
public enum QuantityPrefix {

    @XmlEnumValue("ana")
    ANA("ana"),
    @XmlEnumValue("ana ad")
    ANA_AD("ana ad"),
    @XmlEnumValue("ad")
    AD("ad"),
    @XmlEnumValue("qs")
    QS("qs");
    private final String value;

    QuantityPrefix(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QuantityPrefix fromValue(String v) {
        for (QuantityPrefix c: QuantityPrefix.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
