//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.19 at 04:08:15 PM CEST 
//


package be.apb.standards.smoa.schema.v1;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for QuantityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuantityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="decimal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="unit" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;enumeration value="%"/>
 *               &lt;enumeration value="%vv"/>
 *               &lt;enumeration value="%wv"/>
 *               &lt;enumeration value="%ww"/>
 *               &lt;enumeration value="1000/mm3"/>
 *               &lt;enumeration value="mg/dl"/>
 *               &lt;enumeration value="amp"/>
 *               &lt;enumeration value="bag"/>
 *               &lt;enumeration value="bitperminute"/>
 *               &lt;enumeration value="bol"/>
 *               &lt;enumeration value="bot"/>
 *               &lt;enumeration value="box"/>
 *               &lt;enumeration value="c"/>
 *               &lt;enumeration value="can"/>
 *               &lt;enumeration value="cap"/>
 *               &lt;enumeration value="cc"/>
 *               &lt;enumeration value="cm"/>
 *               &lt;enumeration value="cmm"/>
 *               &lt;enumeration value="cnt"/>
 *               &lt;enumeration value="ctr"/>
 *               &lt;enumeration value="daily"/>
 *               &lt;enumeration value="day"/>
 *               &lt;enumeration value="spoon"/>
 *               &lt;enumeration value="week"/>
 *               &lt;enumeration value="month"/>
 *               &lt;enumeration value="degree"/>
 *               &lt;enumeration value="dis"/>
 *               &lt;enumeration value="drm"/>
 *               &lt;enumeration value="fl"/>
 *               &lt;enumeration value="fld"/>
 *               &lt;enumeration value="flo"/>
 *               &lt;enumeration value="ftc"/>
 *               &lt;enumeration value="fts"/>
 *               &lt;enumeration value="g/dl"/>
 *               &lt;enumeration value="mg"/>
 *               &lt;enumeration value="mg/ml"/>
 *               &lt;enumeration value="mg/l"/>
 *               &lt;enumeration value="mg/m2"/>
 *               &lt;enumeration value="minute"/>
 *               &lt;enumeration value="mm"/>
 *               &lt;enumeration value="mm/h"/>
 *               &lt;enumeration value="mmhg"/>
 *               &lt;enumeration value="second"/>
 *               &lt;enumeration value="millisecond"/>
 *               &lt;enumeration value="hour"/>
 *               &lt;enumeration value="goutte"/>
 *               &lt;enumeration value="ml"/>
 *               &lt;enumeration value="ctg"/>
 *               &lt;enumeration value="gal"/>
 *               &lt;enumeration value="gm"/>
 *               &lt;enumeration value="gr"/>
 *               &lt;enumeration value="in"/>
 *               &lt;enumeration value="inc"/>
 *               &lt;enumeration value="jar"/>
 *               &lt;enumeration value="kg"/>
 *               &lt;enumeration value="kit"/>
 *               &lt;enumeration value="l"/>
 *               &lt;enumeration value="lb"/>
 *               &lt;enumeration value="lm"/>
 *               &lt;enumeration value="loz"/>
 *               &lt;enumeration value="mcg"/>
 *               &lt;enumeration value="mcl"/>
 *               &lt;enumeration value="mcm"/>
 *               &lt;enumeration value="mcn"/>
 *               &lt;enumeration value="meq"/>
 *               &lt;enumeration value="mic"/>
 *               &lt;enumeration value="mil"/>
 *               &lt;enumeration value="min"/>
 *               &lt;enumeration value="mis"/>
 *               &lt;enumeration value="mmo"/>
 *               &lt;enumeration value="mol"/>
 *               &lt;enumeration value="nl"/>
 *               &lt;enumeration value="nmg"/>
 *               &lt;enumeration value="nmo"/>
 *               &lt;enumeration value="ns"/>
 *               &lt;enumeration value="oz"/>
 *               &lt;enumeration value="pel"/>
 *               &lt;enumeration value="pg"/>
 *               &lt;enumeration value="pkg"/>
 *               &lt;enumeration value="pnu"/>
 *               &lt;enumeration value="ppm"/>
 *               &lt;enumeration value="pt"/>
 *               &lt;enumeration value="qs"/>
 *               &lt;enumeration value="qt"/>
 *               &lt;enumeration value="sat"/>
 *               &lt;enumeration value="spr"/>
 *               &lt;enumeration value="sqc"/>
 *               &lt;enumeration value="stp"/>
 *               &lt;enumeration value="sup"/>
 *               &lt;enumeration value="syr"/>
 *               &lt;enumeration value="tab"/>
 *               &lt;enumeration value="tbl"/>
 *               &lt;enumeration value="tes"/>
 *               &lt;enumeration value="ton"/>
 *               &lt;enumeration value="tpn"/>
 *               &lt;enumeration value="trc"/>
 *               &lt;enumeration value="tro"/>
 *               &lt;enumeration value="tsp"/>
 *               &lt;enumeration value="tub"/>
 *               &lt;enumeration value="umg"/>
 *               &lt;enumeration value="unt"/>
 *               &lt;enumeration value="vil"/>
 *               &lt;enumeration value="vpr"/>
 *               &lt;enumeration value="waf"/>
 *               &lt;enumeration value="x"/>
 *               &lt;enumeration value="ydl"/>
 *               &lt;enumeration value="yds"/>
 *               &lt;enumeration value="ondemand"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuantityType", propOrder = {
    "decimal",
    "unit"
})
public class QuantityType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected BigDecimal decimal;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String unit;

    /**
     * Gets the value of the decimal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDecimal() {
        return decimal;
    }

    /**
     * Sets the value of the decimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDecimal(BigDecimal value) {
        this.decimal = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

}
