//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.10 at 01:53:52 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.gfddpp.be/getconfiguration/v1")
package be.apb.standards.gfddpp.request.configuration;
