//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 03:52:20 PM CEST 
//


package uz.ehealth.ritme.be.fgov.ehealth.aa.complextype.v1;

import uz.ehealth.ritme.oasis.names.tc.saml._2_0.assertion.AttributeType;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * Metadata on supported quality.
 * 
 * <p>Java class for QualityDescriberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QualityDescriberType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:be:fgov:ehealth:aa:complextype:v1}QualityTypeCode" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:be:fgov:ehealth:aa:complextype:v1}QualityTypeFriendlyName" maxOccurs="unbounded"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:2.0:assertion}Attribute" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("ALL") //Generated file
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualityDescriberType", propOrder = {
    "qualityTypeCode",
    "qualityTypeFriendlyName",
    "attribute"
})
@XmlSeeAlso({
    SupportedQualityType.class
})
public class QualityDescriberType {

    @XmlElement(name = "QualityTypeCode", required = true)
    protected List<TypeCodeType> qualityTypeCode;
    @XmlElement(name = "QualityTypeFriendlyName", required = true)
    protected List<NameType> qualityTypeFriendlyName;
    @XmlElement(name = "Attribute", namespace = "urn:oasis:names:tc:SAML:2.0:assertion", required = true)
    protected List<AttributeType> attribute;

    /**
     * Gets the value of the qualityTypeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualityTypeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualityTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeCodeType }
     * 
     * 
     */
    public List<TypeCodeType> getQualityTypeCode() {
        if (qualityTypeCode == null) {
            qualityTypeCode = new ArrayList<TypeCodeType>();
        }
        return this.qualityTypeCode;
    }

    /**
     * Gets the value of the qualityTypeFriendlyName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualityTypeFriendlyName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualityTypeFriendlyName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getQualityTypeFriendlyName() {
        if (qualityTypeFriendlyName == null) {
            qualityTypeFriendlyName = new ArrayList<NameType>();
        }
        return this.qualityTypeFriendlyName;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeType }
     * 
     * 
     */
    public List<AttributeType> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<AttributeType>();
        }
        return this.attribute;
    }

}
