//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.08 at 03:42:41 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.gfddpp.be")
package be.apb.standards.gfddpp.patient.signature;
