//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.30 at 02:56:43 PM CEST 
//


package be.apb.gfddpp.systemservices.v2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="systemServicesList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="systemServicesEntry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="system">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="systemType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="service" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="URI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="contractList" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="contractEntry" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="contractType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="contractPartyList">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="contractPartyEntry" maxOccurs="unbounded">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="contractPartyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                     &lt;element name="contractPartyID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "systemServicesList"
})
@XmlRootElement(name = "systemServices")
public class SystemServices
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar version;
    @XmlElement(required = true)
    protected SystemServices.SystemServicesList systemServicesList;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVersion(XMLGregorianCalendar value) {
        this.version = value;
    }

    /**
     * Gets the value of the systemServicesList property.
     * 
     * @return
     *     possible object is
     *     {@link SystemServices.SystemServicesList }
     *     
     */
    public SystemServices.SystemServicesList getSystemServicesList() {
        return systemServicesList;
    }

    /**
     * Sets the value of the systemServicesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemServices.SystemServicesList }
     *     
     */
    public void setSystemServicesList(SystemServices.SystemServicesList value) {
        this.systemServicesList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="systemServicesEntry" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="system">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="systemType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="service" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="URI" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="contractList" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="contractEntry" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="contractType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="contractPartyList">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="contractPartyEntry" maxOccurs="unbounded">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="contractPartyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                           &lt;element name="contractPartyID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "systemServicesEntry"
    })
    public static class SystemServicesList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected List<SystemServices.SystemServicesList.SystemServicesEntry> systemServicesEntry;

        /**
         * Gets the value of the systemServicesEntry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the systemServicesEntry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSystemServicesEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SystemServices.SystemServicesList.SystemServicesEntry }
         * 
         * 
         */
        public List<SystemServices.SystemServicesList.SystemServicesEntry> getSystemServicesEntry() {
            if (systemServicesEntry == null) {
                systemServicesEntry = new ArrayList<SystemServices.SystemServicesList.SystemServicesEntry>();
            }
            return this.systemServicesEntry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="system">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="systemType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="service" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="URI" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="contractList" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="contractEntry" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="contractType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="contractPartyList">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="contractPartyEntry" maxOccurs="unbounded">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="contractPartyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                                 &lt;element name="contractPartyID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "system",
            "service",
            "contractList"
        })
        public static class SystemServicesEntry
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(required = true)
            protected SystemServices.SystemServicesList.SystemServicesEntry.System system;
            @XmlElement(required = true)
            protected List<SystemServices.SystemServicesList.SystemServicesEntry.Service> service;
            protected SystemServices.SystemServicesList.SystemServicesEntry.ContractList contractList;

            /**
             * Gets the value of the system property.
             * 
             * @return
             *     possible object is
             *     {@link SystemServices.SystemServicesList.SystemServicesEntry.System }
             *     
             */
            public SystemServices.SystemServicesList.SystemServicesEntry.System getSystem() {
                return system;
            }

            /**
             * Sets the value of the system property.
             * 
             * @param value
             *     allowed object is
             *     {@link SystemServices.SystemServicesList.SystemServicesEntry.System }
             *     
             */
            public void setSystem(SystemServices.SystemServicesList.SystemServicesEntry.System value) {
                this.system = value;
            }

            /**
             * Gets the value of the service property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the service property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getService().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SystemServices.SystemServicesList.SystemServicesEntry.Service }
             * 
             * 
             */
            public List<SystemServices.SystemServicesList.SystemServicesEntry.Service> getService() {
                if (service == null) {
                    service = new ArrayList<SystemServices.SystemServicesList.SystemServicesEntry.Service>();
                }
                return this.service;
            }

            /**
             * Gets the value of the contractList property.
             * 
             * @return
             *     possible object is
             *     {@link SystemServices.SystemServicesList.SystemServicesEntry.ContractList }
             *     
             */
            public SystemServices.SystemServicesList.SystemServicesEntry.ContractList getContractList() {
                return contractList;
            }

            /**
             * Sets the value of the contractList property.
             * 
             * @param value
             *     allowed object is
             *     {@link SystemServices.SystemServicesList.SystemServicesEntry.ContractList }
             *     
             */
            public void setContractList(SystemServices.SystemServicesList.SystemServicesEntry.ContractList value) {
                this.contractList = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="contractEntry" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="contractType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="contractPartyList">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="contractPartyEntry" maxOccurs="unbounded">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="contractPartyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                       &lt;element name="contractPartyID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "contractEntry"
            })
            public static class ContractList
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(required = true)
                protected List<SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry> contractEntry;

                /**
                 * Gets the value of the contractEntry property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the contractEntry property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContractEntry().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry }
                 * 
                 * 
                 */
                public List<SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry> getContractEntry() {
                    if (contractEntry == null) {
                        contractEntry = new ArrayList<SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry>();
                    }
                    return this.contractEntry;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="contractType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="contractPartyList">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="contractPartyEntry" maxOccurs="unbounded">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="contractPartyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                             &lt;element name="contractPartyID" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "contractType",
                    "contractPartyList"
                })
                public static class ContractEntry
                    implements Serializable
                {

                    private final static long serialVersionUID = 1L;
                    @XmlElement(required = true)
                    protected String contractType;
                    @XmlElement(required = true)
                    protected SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry.ContractPartyList contractPartyList;

                    /**
                     * Gets the value of the contractType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getContractType() {
                        return contractType;
                    }

                    /**
                     * Sets the value of the contractType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setContractType(String value) {
                        this.contractType = value;
                    }

                    /**
                     * Gets the value of the contractPartyList property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry.ContractPartyList }
                     *     
                     */
                    public SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry.ContractPartyList getContractPartyList() {
                        return contractPartyList;
                    }

                    /**
                     * Sets the value of the contractPartyList property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry.ContractPartyList }
                     *     
                     */
                    public void setContractPartyList(SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry.ContractPartyList value) {
                        this.contractPartyList = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="contractPartyEntry" maxOccurs="unbounded">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="contractPartyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                   &lt;element name="contractPartyID" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "contractPartyEntry"
                    })
                    public static class ContractPartyList
                        implements Serializable
                    {

                        private final static long serialVersionUID = 1L;
                        @XmlElement(required = true)
                        protected List<SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry.ContractPartyList.ContractPartyEntry> contractPartyEntry;

                        /**
                         * Gets the value of the contractPartyEntry property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the contractPartyEntry property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getContractPartyEntry().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry.ContractPartyList.ContractPartyEntry }
                         * 
                         * 
                         */
                        public List<SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry.ContractPartyList.ContractPartyEntry> getContractPartyEntry() {
                            if (contractPartyEntry == null) {
                                contractPartyEntry = new ArrayList<SystemServices.SystemServicesList.SystemServicesEntry.ContractList.ContractEntry.ContractPartyList.ContractPartyEntry>();
                            }
                            return this.contractPartyEntry;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="contractPartyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *         &lt;element name="contractPartyID" type="{http://www.w3.org/2001/XMLSchema}string"/>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "contractPartyType",
                            "contractPartyID"
                        })
                        public static class ContractPartyEntry
                            implements Serializable
                        {

                            private final static long serialVersionUID = 1L;
                            @XmlElement(required = true)
                            protected String contractPartyType;
                            @XmlElement(required = true)
                            protected String contractPartyID;

                            /**
                             * Gets the value of the contractPartyType property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getContractPartyType() {
                                return contractPartyType;
                            }

                            /**
                             * Sets the value of the contractPartyType property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setContractPartyType(String value) {
                                this.contractPartyType = value;
                            }

                            /**
                             * Gets the value of the contractPartyID property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link String }
                             *     
                             */
                            public String getContractPartyID() {
                                return contractPartyID;
                            }

                            /**
                             * Sets the value of the contractPartyID property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *     
                             */
                            public void setContractPartyID(String value) {
                                this.contractPartyID = value;
                            }

                        }

                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="URI" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "serviceName",
                "uri"
            })
            public static class Service
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(required = true)
                protected String serviceName;
                @XmlElement(name = "URI", required = true)
                protected String uri;

                /**
                 * Gets the value of the serviceName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServiceName() {
                    return serviceName;
                }

                /**
                 * Sets the value of the serviceName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServiceName(String value) {
                    this.serviceName = value;
                }

                /**
                 * Gets the value of the uri property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getURI() {
                    return uri;
                }

                /**
                 * Sets the value of the uri property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setURI(String value) {
                    this.uri = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="systemType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "systemType",
                "systemId"
            })
            public static class System
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(required = true)
                protected String systemType;
                @XmlElement(required = true)
                protected String systemId;

                /**
                 * Gets the value of the systemType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSystemType() {
                    return systemType;
                }

                /**
                 * Sets the value of the systemType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSystemType(String value) {
                    this.systemType = value;
                }

                /**
                 * Gets the value of the systemId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSystemId() {
                    return systemId;
                }

                /**
                 * Sets the value of the systemId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSystemId(String value) {
                    this.systemId = value;
                }

            }

        }

    }

}
