//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.27 at 05:56:16 PM CEST 
//


package be.apb.gfddpp.rtrn.registerdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bvacEventType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bvacEventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sguid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bvacDocument" type="{http://services.gfddpp.be}bvacDocument"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bvacEventType", propOrder = {
    "sguid",
    "bvacDocument"
})
public class BvacEventType {

    @XmlElement(required = true)
    protected String sguid;
    @XmlElement(required = true)
    protected BvacDocument bvacDocument;

    /**
     * Gets the value of the sguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSguid() {
        return sguid;
    }

    /**
     * Sets the value of the sguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSguid(String value) {
        this.sguid = value;
    }

    /**
     * Gets the value of the bvacDocument property.
     * 
     * @return
     *     possible object is
     *     {@link BvacDocument }
     *     
     */
    public BvacDocument getBvacDocument() {
        return bvacDocument;
    }

    /**
     * Sets the value of the bvacDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link BvacDocument }
     *     
     */
    public void setBvacDocument(BvacDocument value) {
        this.bvacDocument = value;
    }

}
