//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 09:11:54 PM CEST 
//


package be.apb.gfddpp.rtrn.registerdata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dispensation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dispensation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="localReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dguid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="product" type="{http://services.gfddpp.be}product"/>
 *           &lt;element name="magistral" type="{http://services.gfddpp.be}magistral"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dispensation", propOrder = {
    "localReference",
    "dguid",
    "product",
    "magistral"
})
public class Dispensation {

    @XmlElement(required = true)
    protected String localReference;
    @XmlElement(required = true)
    protected String dguid;
    protected Product product;
    protected Magistral magistral;

    /**
     * Gets the value of the localReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalReference() {
        return localReference;
    }

    /**
     * Sets the value of the localReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalReference(String value) {
        this.localReference = value;
    }

    /**
     * Gets the value of the dguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDguid() {
        return dguid;
    }

    /**
     * Sets the value of the dguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDguid(String value) {
        this.dguid = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setProduct(Product value) {
        this.product = value;
    }

    /**
     * Gets the value of the magistral property.
     * 
     * @return
     *     possible object is
     *     {@link Magistral }
     *     
     */
    public Magistral getMagistral() {
        return magistral;
    }

    /**
     * Sets the value of the magistral property.
     * 
     * @param value
     *     allowed object is
     *     {@link Magistral }
     *     
     */
    public void setMagistral(Magistral value) {
        this.magistral = value;
    }

}
