//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.01 at 05:41:39 PM CET 
//


package be.apb.gfddpp.servicerouter;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.apb.gfddpp.servicerouter package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.apb.gfddpp.servicerouter
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContractTypes.ContractType.ServiceRoutings }
     * 
     */
    public ContractTypes.ContractType.ServiceRoutings createContractTypesContractTypeServiceRoutings() {
        return new ContractTypes.ContractType.ServiceRoutings();
    }

    /**
     * Create an instance of {@link ContractTypes.ContractType.ServiceRoutings.ServiceRouting }
     * 
     */
    public ContractTypes.ContractType.ServiceRoutings.ServiceRouting createContractTypesContractTypeServiceRoutingsServiceRouting() {
        return new ContractTypes.ContractType.ServiceRoutings.ServiceRouting();
    }

    /**
     * Create an instance of {@link ContractTypes.ContractType }
     * 
     */
    public ContractTypes.ContractType createContractTypesContractType() {
        return new ContractTypes.ContractType();
    }

    /**
     * Create an instance of {@link ContractTypes }
     * 
     */
    public ContractTypes createContractTypes() {
        return new ContractTypes();
    }

}
