//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.20 at 08:24:00 PM CEST 
//


package be.apb.gfddpp.assuralia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SingleMessageMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleMessageMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="EncryptedSingleMessage" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleMessageMap", propOrder = {
    "key",
    "encryptedSingleMessage"
})
public class SingleMessageMap {

    @XmlElement(name = "Key", required = true)
    protected byte[] key;
    @XmlElement(name = "EncryptedSingleMessage", required = true)
    protected byte[] encryptedSingleMessage;

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setKey(byte[] value) {
        this.key = ((byte[]) value);
    }

    /**
     * Gets the value of the encryptedSingleMessage property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getEncryptedSingleMessage() {
        return encryptedSingleMessage;
    }

    /**
     * Sets the value of the encryptedSingleMessage property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setEncryptedSingleMessage(byte[] value) {
        this.encryptedSingleMessage = ((byte[]) value);
    }

}
