//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.08 at 04:15:31 PM CEST 
//


package be.apb.gfddpp.productfilter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="white-list" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="medicines" type="{}medicines" minOccurs="0"/>
 *                   &lt;element name="preparations" type="{}preparations" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="black-list" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ranges" type="{}ranges" minOccurs="0"/>
 *                   &lt;element name="medicines" type="{}medicines" minOccurs="0"/>
 *                   &lt;element name="preparations" type="{}preparations" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productList", propOrder = {
    "whiteList",
    "blackList"
})
public class ProductList {

    @XmlElement(name = "white-list")
    protected ProductList.WhiteList whiteList;
    @XmlElement(name = "black-list")
    protected ProductList.BlackList blackList;

    /**
     * Gets the value of the whiteList property.
     * 
     * @return
     *     possible object is
     *     {@link ProductList.WhiteList }
     *     
     */
    public ProductList.WhiteList getWhiteList() {
        return whiteList;
    }

    /**
     * Sets the value of the whiteList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductList.WhiteList }
     *     
     */
    public void setWhiteList(ProductList.WhiteList value) {
        this.whiteList = value;
    }

    /**
     * Gets the value of the blackList property.
     * 
     * @return
     *     possible object is
     *     {@link ProductList.BlackList }
     *     
     */
    public ProductList.BlackList getBlackList() {
        return blackList;
    }

    /**
     * Sets the value of the blackList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductList.BlackList }
     *     
     */
    public void setBlackList(ProductList.BlackList value) {
        this.blackList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ranges" type="{}ranges" minOccurs="0"/>
     *         &lt;element name="medicines" type="{}medicines" minOccurs="0"/>
     *         &lt;element name="preparations" type="{}preparations" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ranges",
        "medicines",
        "preparations"
    })
    public static class BlackList {

        protected Ranges ranges;
        protected Medicines medicines;
        protected Preparations preparations;

        /**
         * Gets the value of the ranges property.
         * 
         * @return
         *     possible object is
         *     {@link Ranges }
         *     
         */
        public Ranges getRanges() {
            return ranges;
        }

        /**
         * Sets the value of the ranges property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ranges }
         *     
         */
        public void setRanges(Ranges value) {
            this.ranges = value;
        }

        /**
         * Gets the value of the medicines property.
         * 
         * @return
         *     possible object is
         *     {@link Medicines }
         *     
         */
        public Medicines getMedicines() {
            return medicines;
        }

        /**
         * Sets the value of the medicines property.
         * 
         * @param value
         *     allowed object is
         *     {@link Medicines }
         *     
         */
        public void setMedicines(Medicines value) {
            this.medicines = value;
        }

        /**
         * Gets the value of the preparations property.
         * 
         * @return
         *     possible object is
         *     {@link Preparations }
         *     
         */
        public Preparations getPreparations() {
            return preparations;
        }

        /**
         * Sets the value of the preparations property.
         * 
         * @param value
         *     allowed object is
         *     {@link Preparations }
         *     
         */
        public void setPreparations(Preparations value) {
            this.preparations = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="medicines" type="{}medicines" minOccurs="0"/>
     *         &lt;element name="preparations" type="{}preparations" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "medicines",
        "preparations"
    })
    public static class WhiteList {

        protected Medicines medicines;
        protected Preparations preparations;

        /**
         * Gets the value of the medicines property.
         * 
         * @return
         *     possible object is
         *     {@link Medicines }
         *     
         */
        public Medicines getMedicines() {
            return medicines;
        }

        /**
         * Sets the value of the medicines property.
         * 
         * @param value
         *     allowed object is
         *     {@link Medicines }
         *     
         */
        public void setMedicines(Medicines value) {
            this.medicines = value;
        }

        /**
         * Gets the value of the preparations property.
         * 
         * @return
         *     possible object is
         *     {@link Preparations }
         *     
         */
        public Preparations getPreparations() {
            return preparations;
        }

        /**
         * Sets the value of the preparations property.
         * 
         * @param value
         *     allowed object is
         *     {@link Preparations }
         *     
         */
        public void setPreparations(Preparations value) {
            this.preparations = value;
        }

    }

}
