//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.id.v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				http://www.fagg-afmps.be/nl/items/gegevensbank_vergunde_geneesmiddelen/index.jsp
 * 			
 * 
 * <p>Java class for BeRegistrationIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeRegistrationIdType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.apb.be/standards/smoa/schema/id/v1}Abstract-MedicinalProductIdType">
 *       &lt;sequence>
 *         &lt;element name="cti" type="{http://www.apb.be/standards/smoa/schema/v1}BeMedicinalProductRegistrationNumberType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeRegistrationIdType", propOrder = {
    "cti"
})
public class BeRegistrationIdType
    extends AbstractMedicinalProductIdType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int cti;

    /**
     * Gets the value of the cti property.
     * 
     */
    public int getCti() {
        return cti;
    }

    /**
     * Sets the value of the cti property.
     * 
     */
    public void setCti(int value) {
        this.cti = value;
    }

}
