//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.id.v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocalPrescriptionIdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocalPrescriptionIdType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.apb.be/standards/smoa/schema/id/v1}Abstract-PrescriptionIdType">
 *       &lt;sequence>
 *         &lt;element name="officinaOrderNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="officina" type="{http://www.apb.be/standards/smoa/schema/id/v1}Abstract-PharmacyIdType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocalPrescriptionIdType", propOrder = {
    "officinaOrderNumber",
    "officina"
})
public class LocalPrescriptionIdType
    extends AbstractPrescriptionIdType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int officinaOrderNumber;
    @XmlElement(required = true)
    protected AbstractPharmacyIdType officina;

    /**
     * Gets the value of the officinaOrderNumber property.
     * 
     */
    public int getOfficinaOrderNumber() {
        return officinaOrderNumber;
    }

    /**
     * Sets the value of the officinaOrderNumber property.
     * 
     */
    public void setOfficinaOrderNumber(int value) {
        this.officinaOrderNumber = value;
    }

    /**
     * Gets the value of the officina property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractPharmacyIdType }
     *     
     */
    public AbstractPharmacyIdType getOfficina() {
        return officina;
    }

    /**
     * Sets the value of the officina property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractPharmacyIdType }
     *     
     */
    public void setOfficina(AbstractPharmacyIdType value) {
        this.officina = value;
    }

}
