//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 03:52:20 PM CEST 
//


package uz.ehealth.ritme.be.fgov.ehealth.addressbook.protocol.v1;

import uz.ehealth.ritme.be.fgov.ehealth.addressbook.core.v1.IndividualContactInformationType;
import uz.ehealth.ritme.be.fgov.ehealth.commons.protocol.v2.StatusResponseType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Return healthcare professional contact data
 * 
 * <p>Java class for GetProfessionalContactInfoResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetProfessionalContactInfoResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:commons:protocol:v2}StatusResponseType">
 *       &lt;sequence>
 *         &lt;element name="IndividualContactInformation" type="{urn:be:fgov:ehealth:addressbook:core:v1}IndividualContactInformationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("ALL") //Generated file
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetProfessionalContactInfoResponseType", propOrder = {
    "individualContactInformation"
})
public class GetProfessionalContactInfoResponseType
    extends StatusResponseType
{

    @XmlElement(name = "IndividualContactInformation")
    protected IndividualContactInformationType individualContactInformation;

    /**
     * Gets the value of the individualContactInformation property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualContactInformationType }
     *     
     */
    public IndividualContactInformationType getIndividualContactInformation() {
        return individualContactInformation;
    }

    /**
     * Sets the value of the individualContactInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualContactInformationType }
     *     
     */
    public void setIndividualContactInformation(IndividualContactInformationType value) {
        this.individualContactInformation = value;
    }

}
