//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.13 at 03:52:20 PM CEST 
//


package uz.ehealth.ritme.be.fgov.ehealth.addressbook.protocol.v1;

import uz.ehealth.ritme.be.fgov.ehealth.aa.complextype.v1.HealthCareOrganizationTypeV2;
import uz.ehealth.ritme.be.fgov.ehealth.commons.protocol.v2.PaginationStatusResponseType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Return all healthcare organizations that macth to a given set of criteria
 * 
 * <p>Java class for SearchOrganizationsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchOrganizationsResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:commons:protocol:v2}PaginationStatusResponseType">
 *       &lt;sequence>
 *         &lt;element name="HealthCareOrganization" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:be:fgov:ehealth:aa:complextype:v1}HealthCareOrganizationTypeV2">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("ALL") //Generated file
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchOrganizationsResponseType", propOrder = {
    "healthCareOrganization"
})
public class SearchOrganizationsResponseType
    extends PaginationStatusResponseType
{

    @XmlElement(name = "HealthCareOrganization")
    protected List<HealthCareOrganization> healthCareOrganization;

    /**
     * Gets the value of the healthCareOrganization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the healthCareOrganization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHealthCareOrganization().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HealthCareOrganization }
     * 
     * 
     */
    public List<HealthCareOrganization> getHealthCareOrganization() {
        if (healthCareOrganization == null) {
            healthCareOrganization = new ArrayList<HealthCareOrganization>();
        }
        return this.healthCareOrganization;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:be:fgov:ehealth:aa:complextype:v1}HealthCareOrganizationTypeV2">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class HealthCareOrganization
        extends HealthCareOrganizationTypeV2
    {


    }

}
