//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 07:02:16 PM CET 
//


package be.apb.gfddpp.systemservices;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="systemServicesList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="systemServicesEntry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="system">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="URI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="service">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="systemIdType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "systemServicesList"
})
@XmlRootElement(name = "systemServices")
public class SystemServices
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar version;
    @XmlElement(required = true)
    protected SystemServices.SystemServicesList systemServicesList;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVersion(XMLGregorianCalendar value) {
        this.version = value;
    }

    /**
     * Gets the value of the systemServicesList property.
     * 
     * @return
     *     possible object is
     *     {@link SystemServices.SystemServicesList }
     *     
     */
    public SystemServices.SystemServicesList getSystemServicesList() {
        return systemServicesList;
    }

    /**
     * Sets the value of the systemServicesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemServices.SystemServicesList }
     *     
     */
    public void setSystemServicesList(SystemServices.SystemServicesList value) {
        this.systemServicesList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="systemServicesEntry" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="system">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="URI" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="service">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="systemIdType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "systemServicesEntry"
    })
    public static class SystemServicesList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected List<SystemServices.SystemServicesList.SystemServicesEntry> systemServicesEntry;

        /**
         * Gets the value of the systemServicesEntry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the systemServicesEntry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSystemServicesEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SystemServices.SystemServicesList.SystemServicesEntry }
         * 
         * 
         */
        public List<SystemServices.SystemServicesList.SystemServicesEntry> getSystemServicesEntry() {
            if (systemServicesEntry == null) {
                systemServicesEntry = new ArrayList<SystemServices.SystemServicesList.SystemServicesEntry>();
            }
            return this.systemServicesEntry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="system">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="URI" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="service">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="systemIdType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "system",
            "service"
        })
        public static class SystemServicesEntry
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(required = true)
            protected SystemServices.SystemServicesList.SystemServicesEntry.System system;
            @XmlElement(required = true)
            protected SystemServices.SystemServicesList.SystemServicesEntry.Service service;

            /**
             * Gets the value of the system property.
             * 
             * @return
             *     possible object is
             *     {@link SystemServices.SystemServicesList.SystemServicesEntry.System }
             *     
             */
            public SystemServices.SystemServicesList.SystemServicesEntry.System getSystem() {
                return system;
            }

            /**
             * Sets the value of the system property.
             * 
             * @param value
             *     allowed object is
             *     {@link SystemServices.SystemServicesList.SystemServicesEntry.System }
             *     
             */
            public void setSystem(SystemServices.SystemServicesList.SystemServicesEntry.System value) {
                this.system = value;
            }

            /**
             * Gets the value of the service property.
             * 
             * @return
             *     possible object is
             *     {@link SystemServices.SystemServicesList.SystemServicesEntry.Service }
             *     
             */
            public SystemServices.SystemServicesList.SystemServicesEntry.Service getService() {
                return service;
            }

            /**
             * Sets the value of the service property.
             * 
             * @param value
             *     allowed object is
             *     {@link SystemServices.SystemServicesList.SystemServicesEntry.Service }
             *     
             */
            public void setService(SystemServices.SystemServicesList.SystemServicesEntry.Service value) {
                this.service = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="systemIdType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="systemId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "systemIdType",
                "systemId"
            })
            public static class Service
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(required = true)
                protected String systemIdType;
                @XmlElement(required = true)
                protected String systemId;

                /**
                 * Gets the value of the systemIdType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSystemIdType() {
                    return systemIdType;
                }

                /**
                 * Sets the value of the systemIdType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSystemIdType(String value) {
                    this.systemIdType = value;
                }

                /**
                 * Gets the value of the systemId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSystemId() {
                    return systemId;
                }

                /**
                 * Sets the value of the systemId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSystemId(String value) {
                    this.systemId = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="URI" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "serviceName",
                "uri"
            })
            public static class System
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(required = true)
                protected String serviceName;
                @XmlElement(name = "URI", required = true)
                protected String uri;

                /**
                 * Gets the value of the serviceName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getServiceName() {
                    return serviceName;
                }

                /**
                 * Sets the value of the serviceName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setServiceName(String value) {
                    this.serviceName = value;
                }

                /**
                 * Gets the value of the uri property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getURI() {
                    return uri;
                }

                /**
                 * Sets the value of the uri property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setURI(String value) {
                    this.uri = value;
                }

            }

        }

    }

}
