//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 05:20:59 PM CEST 
//


package be.apb.standards.smoa.schema.code.v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecialPrescriptionCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialPrescriptionCodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.apb.be/standards/smoa/schema/code/v1}Abstract-SpecialPrescriptionCodeType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.apb.be/standards/smoa/schema/code/v1}SPECIALPRESCRIPTIONTYPE"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialPrescriptionCodeType", propOrder = {
    "type"
})
public class SpecialPrescriptionCodeType
    extends AbstractSpecialPrescriptionCodeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected SPECIALPRESCRIPTIONTYPE type;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SPECIALPRESCRIPTIONTYPE }
     *     
     */
    public SPECIALPRESCRIPTIONTYPE getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPECIALPRESCRIPTIONTYPE }
     *     
     */
    public void setType(SPECIALPRESCRIPTIONTYPE value) {
        this.type = value;
    }

}
